### ISSUE TITLE
On some resolutions server list is not responsive

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#10]
### Current Behavior

![image](https://user-images.githubusercontent.com/66617078/174435668-16904d6e-e141-4cdf-aff2-c5b4b89eef37.png)

The server list is on the sidebar

### Expected Behavior

Change the sidebar to the topnav that is on mobile devieces

### Steps to Reproduce

Open Inspect Element > Deviece Toolbar > Responsive > Set your resolution to 1393x1080

### Panel Version

3.0.1

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Unable to reproduce using selected resolution on Firefox.
![image](https://cdn.discordapp.com/attachments/887033539252588555/987682652796616774/unknown.png)

**Comment by OlekAleksander** [comment]
Happens to me while using opera.

**Comment by OlekAleksander** [comment]
![image](https://user-images.githubusercontent.com/66617078/174436178-38ad8fae-e556-4db4-aa4e-beed0ff3dafc.png)

**Comment by OlekAleksander** [comment]
Yeah, only happens on opera, seems to be an browser issue, Closing.
