### ISSUE TITLE
Discord webhook alert 

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#100]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Discord webhook alert when someone register while we have approval enabled. so this will help to approve that user faster.

### Describe the solution you'd like.

A alert send through discord webhook when user register into panel while we have approval enable.

### Additional context to this request.

NoPe

**Comment by TheFallenSpirit** [comment]
I will build this, have lots of experience with webhooks.

**Comment by camwhi-te** [comment]
Closed in #103
