### ISSUE TITLE
Adding a egg

### ISSUE THREAD

**Issue by aidanw-dev** [Jexactyl/Jexactyl#102]
### Current Behavior

When I add an egg the Associated Nest droop down menu is cut off. I am on Chrome
![Screenshot (9)](https://user-images.githubusercontent.com/61997640/185017506-a226e72a-4915-4b7f-9637-04a05f9549a7.png)
 

### Expected Behavior

 the Associated Nest drop down menu is not suppose to be cut off

### Steps to Reproduce

go to Nest and when you go to import the egg its there

### Panel Version

3.4.2

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by kry008** [comment]
I have the same problem. I set up everything from docs.
![image](https://user-images.githubusercontent.com/25504684/185075004-32247526-39bf-45e2-853e-be6d4285c88c.png)

**Comment by camwhi-te** [comment]
![image](https://user-images.githubusercontent.com/72230943/186785933-068fcbbc-5429-4e03-b4ee-4d5fdc7abbaf.png)
Huh, unable to replicate. This may be because it's fixed on develop.

**Comment by camwhi-te** [comment]
Fixed on develop
