### ISSUE TITLE
Loggin in with discord auth2

### ISSUE THREAD

**Issue by aidanw-dev** [Jexactyl/Jexactyl#106]
### Current Behavior

When I authenticate with discord and click approve I get redirected to this
<img width="1440" alt="Screen Shot 2022-08-17 at 4 15 56 PM" src="https://user-images.githubusercontent.com/61997640/185234611-da391138-a92b-4875-b8fa-864d6db8b631.png">
 

### Expected Behavior

It supposes to redirect me to the panel

### Steps to Reproduce

Go to the login page on the panel. click authenticate with discord, log in with discord and when you click approve it should happen 

### Panel Version

3.4.2

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheFallenSpirit** [comment]
Cannot replicate, Discord OAuth seems to be working fine for me on the latest version. Have you linked your Discord account to your panel account?

**Comment by aidanw-dev** [comment]
I do not think so, But this is with other people who are trying to register with discord and it redirects them to the blank page. You can try the website https://panel.skyhosting.org

**Comment by camwhi-te** [comment]
Error logs will be necessary to look into this. 👍

**Comment by Mrfixit935** [comment]
How do I get the log

**Comment by aidanw-dev** [comment]
root@vmi905133:/var/www/pterodactyl# tail -n 100 /var/www/pterodactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99
tail: cannot open '/var/www/pterodactyl/storage/logs/laravel-2022-08-23.log' for reading: No such file or directory
Use netcat.
root@vmi905133:/var/www/pterodactyl#
