### ISSUE TITLE
Display plugins logo on the Plugin installer

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#107]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Display a small logo of the plugin.

### Describe the solution you'd like.

A small logo placed below the name of the plugin.

**Comment by camwhi-te** [comment]
![image](https://user-images.githubusercontent.com/72230943/186786838-8de542ca-8558-4c11-9ae0-a714245d270e.png)
To my knowledge, the Spiget API doesn't send this data over. I'll look at it in the future though.
