### ISSUE TITLE
Store page do not enable stripe/paypal integrations even when enabled.

### ISSUE THREAD

**Issue by kodxana** [Jexactyl/Jexactyl#108]
### Current Behavior

The config .env file got filled with correct keys and paypal/stripe integration got enabled from web UI too though when coming to store page gateway are not enabled.

### Expected Behavior

After filling correct values gateway should be showing up on storage page

### Steps to Reproduce

Follow guide to setup stripe/paypal integration and go to store page

### Panel Version

3.4.2

### Wings Version

20.10.5+dfsg1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Antoniovbn000** [comment]
What is wrong with your wings version?

**Comment by camwhi-te** [comment]
Resolved in 7eaf9ac2b99ef8176fa125d0e4779860b3143688
