### ISSUE TITLE
Making a server different egg in a different nest

### ISSUE THREAD

**Issue by aidanw-dev** [Jexactyl/Jexactyl#112]
### Current Behavior

I make a MongoDB server that is in a database nest but it comes up as a bungee server that is in a Minecraft nest
![Screenshot (11)](https://user-images.githubusercontent.com/61997640/186026885-63052187-a839-4325-9e5c-a21c9601029e.png)
![Screenshot (12)](https://user-images.githubusercontent.com/61997640/186026897-b220fe01-6282-42a6-9d42-82bf741a9196.png)
![Screenshot (13)](https://user-images.githubusercontent.com/61997640/186026946-9db60db1-c9ae-4ce2-a5d1-ba7905359209.png)
 

### Expected Behavior

It supposes to be a MongoDB server, not a bungee cord server

### Steps to Reproduce

I do not really know how to explain it because everyone's panel is different, a picture will be below to show what mine looks like
![Screenshot (14)](https://user-images.githubusercontent.com/61997640/186027896-318ef55d-863b-499d-b983-ffae9b2b71eb.png)

make a database server and it should be a bungee cord server 

### Panel Version

3.4.2

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Issue with your configuration

**Comment by aidanw-dev** [comment]
Not its not, what configuration
