### ISSUE TITLE
Servers deleted using admin api doesn't return the resources.

### ISSUE THREAD

**Issue by r-kjha** [Jexactyl/Jexactyl#113]
### Current Behavior

RAM, Disk, CPU, etc are not returned to the user account if their server is deleted using admin api key.

### Expected Behavior

Return resources even if the server is deleted using api

### Steps to Reproduce

create a server.
delete the server using admin api
https://dashflo.net/docs/api/pterodactyl/v1/
check if the resources are returned or not

### Panel Version

3.4.2

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Surely you must see the inconsistency in this... if the server is deleted, where exactly is the panel supposed to get the resource usage from?

**Comment by r-kjha** [comment]
![image](https://user-images.githubusercontent.com/87710356/186367623-045b0eae-c2bc-4632-87aa-d70d415fd354.png)

the api should be able to return resources too if the server is deleted. same as in the ss

**Comment by devnote-dev** [comment]
Oh I see, I assumed you meant the server resource usage (in the client API).

**Comment by camwhi-te** [comment]
Resolved in ce60f667a7cf08ff2f31495f7018cf64eece586f
