### ISSUE TITLE
Client api key actions not displaying correctly in dashboard subnavigation

### ISSUE THREAD

**Issue by b4dsk** [Jexactyl/Jexactyl#117]
### Current Behavior

- API key creation actions do not show correctly in the subnavigation
![image](https://user-images.githubusercontent.com/103528714/186718514-f7c4f8a4-a1d4-49cc-b96a-13e6d1eff2ac.png)

### Expected Behavior

- It should show the description of the key, not {{identifier}}

### Steps to Reproduce

1. Create a client API key
2. Look at the subnavigation on dashboard

### Panel Version

3.4.2

### Wings Version

1.7.0

### Games and/or Eggs Affected

All

### Docker Image

No need

### Error Logs

```bash
No need
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
Resolved in e4914ba3f0d450429d0d074ec060beaf07c45f65
