### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#12]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A progress bar that shows the file upload status. (File manager)

### Describe the solution you'd like.

Under the loading bar there should be an text wich says: file out of files, Estimated time: time

**Comment by babyharpsea** [comment]
There's already an addon on Pteromarket for that so it'll be kind of bad for the addon author but doesn't seem like a bad idea (files out of files) hence the addon just displays the mbs out of mbs and a percentage of how many progress is done.

**Comment by camwhi-te** [comment]
@babyharpsea There's already open-source repositories holding the code, and I've gone ahead and implemented the progress bar from the v2 branch on Pterodactyl.

**Comment by camwhi-te** [comment]
@OlekAleksander implemented in 7b4915368db6bfab92d0a3171902d4091e4c689c, needs testing though.

**Comment by babyharpsea** [comment]
> @babyharpsea There's already open-source repositories holding the code, and I've gone ahead and implemented the progress bar from the v2 branch on Pterodactyl.

Ah, alright! 👍

**Comment by camwhi-te** [comment]
Closed as completed
