### ISSUE TITLE
Email confirmation after register

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#123]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

An feature to verify email adresses before using the panel. This feature would increase the security and will ensure that no one creates account with not their email adresses. This would help preventing alts too.

### Additional context to this request.

An option to enable/disable the feature in the admin panel.

**Comment by OlekAleksander** [comment]
issue 123 btw

**Comment by TheFallenSpirit** [comment]
Issue 123 👌. This sounds like a good idea. I will work on this when I have the time. @cmrxnn please assign to me. Email verification is something I need to so its beneficial for both of us.

**Comment by camwhi-te** [comment]
@TheFallenSpirit Any update on this?

**Comment by OlekAleksander** [comment]
@TheFallenSpirit

**Comment by TheFallenSpirit** [comment]
Ah yes hello, I originally made this and had it completed, however that code was lost. I will recode this when I have time. Just need to know how this would work with the frontend.
