### ISSUE TITLE
More detailed configuration in the server creation page

### ISSUE THREAD

**Issue by TheRealKamisama** [Jexactyl/Jexactyl#128]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The server creation page in jexactyl store are lacking detailed configurations about the egg you chose.  
![1·](https://user-images.githubusercontent.com/35005476/188321853-6398eeb6-0a27-470f-842a-e41187153d55.png)  
As some configuration can only be changed via the server creation page in admin panel.  
![2](https://user-images.githubusercontent.com/35005476/188321946-5e20b6f6-d23f-4e23-a210-de0ed2db5310.png)  
I would like to let the users to configure their server's ports as well as allocations.  
Would you mind adding those configurations to the store page? It will be a great help, thanks.

**Comment by camwhi-te** [comment]
There is intentionally not as much control from the Storefront. Advanced configurations will be left to the admins for multiple reasons:
- The current implementation is functional and does not require this
- Admins should remain to be in full control of their resources and software
- 99% of the time, users will not need access to these settings

Thanks for your understanding.
