### ISSUE TITLE
Renewal price per resource allocated

### ISSUE THREAD

**Issue by AndyIsHereBoi** [Jexactyl/Jexactyl#129]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Servers currently renew based off of a set amount. This can be an issue if someone has a server with 5GB of ram, and someone else has a server with 20GB of ram. They will all be billed at the same price the second time no matter the resources when ones value is way greater then the lesser one.

If servers renew based off resources, it can be easier to have servers that have greater or less resources and bill them as to keep the price per resources standard. If this does not happen it can be hard to bill servers what they are worth if they ALL are being billed off of the same amount.

**Comment by Jonathan5508** [comment]
I agree to this, I want to see this as an upcoming feature.

**Comment by TheRealKamisama** [comment]
Looks like a reasonable improvement, hope to see this.

**Comment by ItzExotical** [comment]
+1 Fully agree. Should definitely be changed.

**Comment by ghost** [comment]
+1 i agree

**Comment by OdileHost** [comment]
+1 i think it's absolutely essential

**Comment by maxencefiu** [comment]
+1 We really need it !

**Comment by camwhi-te** [comment]
Closing for v4
