### ISSUE TITLE
Ability to suspend/unsuspend users 

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#13]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A feature to ban users from the panel

### Describe the solution you'd like.

In users tab a button to suspend a user with a reason

**Comment by OlekAleksander** [comment]
Idk how account suspension system is an low priority.

**Comment by camwhi-te** [comment]
Because I've determined that this issue isn't a major concern in comparison to other issues or features that are in development. Banning accounts won't solve much, as servers can be suspended.
