### ISSUE TITLE
Server background field validation

### ISSUE THREAD

**Issue by wrdg** [Jexactyl/Jexactyl#132]
### Current Behavior

Leaving the server background, under server settings, field blank/null results in the following error:

Bg must be a `string` type, but the final value was: `null`. If "null" is intended as an empty value be sure to mark the schema as `.nullable()`

![Pterodactyl_Panel](https://user-images.githubusercontent.com/49387986/189506267-ac77cf5c-2920-499d-ad48-d4da8350ebed.png)

### Expected Behavior

No validation error upon leaving the field blank

### Steps to Reproduce

* Click within the server background field
* Click outside of the server background field to unfocus the field

### Panel Version

3.4.2

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by AndyIsHereBoi** [comment]
I also noticed this
