### ISSUE TITLE
Remove unnecessary Discord OAuth grants

### ISSUE THREAD

**Issue by wrdg** [Jexactyl/Jexactyl#135]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The Discord registration uses two unnecessary grants: `guilds.join` `guilds`. These grants are not being used in the project, and bring concerns to users who appreciate their privacy and are weary about granting applications these grants.

**Comment by ghost** [comment]
#134 done
