### ISSUE TITLE
Multiple Tabs = More coins

### ISSUE THREAD

**Issue by Karbon1** [Jexactyl/Jexactyl#136]
### Current Behavior

Basically, self-explanatory, We are getting double, triple or even more the coins we are supposed to get depending on the number of tabs of the panel open. It's a major bug and would hurt the economy by a lot.

### Expected Behavior

Should be getting the same amount of coins without multiplying even when having more than one tab of the panel open.

### Steps to Reproduce

Step 1: Login to the panel
Step 2: Open multiple tabs of the panel
Step 3: Wait a bit of time, watch your money/balance be more than Andrew Tate's

### Panel Version

3.4.3

### Wings Version

1.7.x

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Karbon1** [comment]
Apparently it occurs with this version, the version prior to this doesn't have this issue

**Comment by Cainify** [comment]
I can second this, a User of Nero Nodes sent in a video showing this bug in action.
