### ISSUE TITLE
Creating a server from the storefront makes a Minecraft Paper server

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#138]
### Current Behavior

When making a server from the storefront using the official eggs and custom eggs, it has a chance of making a Minecraft Paper server, so you need to pick a different egg in the same nest. Someone already made an issue and it was a configuration error but for some reason, after updating my databases info, the problem still occurs.

### Expected Behavior

Creating a server (for example a Rust server) creates a Paper server, and not a Rust server.

### Steps to Reproduce

Create a server from the storefront and choose any nest but do not change the egg. It creates a Paper server.
![image_2022-09-17_115115786](https://user-images.githubusercontent.com/94217075/190850928-1166327c-61b0-4389-b26f-c9e2c7006cfd.png)

### Panel Version

3.4.3

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
It happens for me too.
But it defaults to the first egg from the first egg (Programing::Python) and the user created an server using purpur and the egg wich was displayed in the admin area said (Minecraft Java::Python)

**Comment by heyitslumi** [comment]
> It happens for me too. But it defaults to the first egg from the first egg (Programing::Python) and the user created an server using purpur and the egg wich was displayed in the admin area said (Minecraft Java::Python)

I can basically agree.

**Comment by OlekAleksander** [comment]
This is an issue for a long time, i reported it on the feedback channel but forgot about creating an issue for it

**Comment by OlekAleksander** [comment]
It didnt happen 3.3.x tho

**Comment by heyitslumi** [comment]
> This is an issue for a long time, i reported it on the feedback channel but forgot about creating an issue for it

i created this issue cause jex refused to fix it if it wasn't reported in github

**Comment by OlekAleksander** [comment]
Seems to be fixed in the latest release

**Comment by camwhi-te** [comment]
I'm also not able to replicate this issue, closing (for now!).

**Comment by OlekAleksander** [comment]
Seems to not be working on a fresh install with some eggs added

**Comment by OlekAleksander** [comment]
Try to create a nginx server on my [host](https://panel.nitronodes.xyz)
It will create a server using the python egg

**Comment by OlekAleksander** [comment]
It's not an issue with the eggs, but it is with the storefront
I can create servers from the admin area, normally
