### ISSUE TITLE
Deleting a server shows up an error

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#139]
### Current Behavior

When deleting a server from the main panel (and not in the admin panel), it shows up an error which is not meant to occur.

### Expected Behavior

The server is supposed to be deleted but instead shows up "The password field is required." when there is no password field.

### Steps to Reproduce

1. Create a server from the storefront or from the admin panel.
2. Go to the server settings and try to delete the server.

### Panel Version

3.4.3

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Karbon1** [comment]
Yeah, I forgot to make a issue about this, but I assume jex forgot to remove that part completely.

**Comment by naysakiu** [comment]
There is a problem as well on the edit , when you try to edit a server configuration as customer is not working.
https://cdn.ignitionhost.ro/biFE4/SOhUCiTO34.PNG

**Comment by camwhi-te** [comment]
@naysaku Please create a separate issue for that.
