### ISSUE TITLE
Rendering page

### ISSUE THREAD

**Issue by CosmicNinja018** [Jexactyl/Jexactyl#140]
### Current Behavior

An error is coming while i am opening my server and on auth page of my panel and the error is "An error was encountered while rendering this page."

### Expected Behavior

It should show the dedicated page

### Steps to Reproduce

mm?

### Panel Version

3.4.3

### Wings Version

1.7.1

### Games and/or Eggs Affected

All

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
Please post the logs

**Comment by camwhi-te** [comment]
Closing until logs are provided.
