### ISSUE TITLE
Creating Custom Source Engine Game server

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#141]
### Current Behavior

Can't create Custom Source Engine Game because here no where field for "Game ID" and i getting error about "The Game ID variable field is required."

### Expected Behavior

Creating server by Game ID dedicated server
Example: Counter Strike: Source

### Steps to Reproduce

Go to storefront and create Custom Source Engine
But no one can't because here no field for Game ID
![IMG_20220920_140345](https://user-images.githubusercontent.com/113983409/191244329-fd6289c9-2dc3-4012-87ca-de7fcf1dd047.jpg)
![IMG_20220920_140532](https://user-images.githubusercontent.com/113983409/191244340-4eab730d-22bb-4111-a8d6-6f959d4b469c.jpg)

### Panel Version

3.4.3

### Wings Version

1.7.0

### Games and/or Eggs Affected

Source Engine (Custom Source Engine Game)

### Docker Image

No response

### Error Logs

```bash
No response
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Setting that variable in egg config to `nullable` will solve this issue. This isn't really a bug with the software, moreso the configuration of the egg you're using.
