### ISSUE TITLE
IPs, email, username and other blacklists / banlist

### ISSUE THREAD

**Issue by MerK2Dev** [Jexactyl/Jexactyl#142]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be wonderful to have an IP, Email, username and other types of blacklist / banlist because there are people banned from hosts but they can login or register again on panel because you cant ban ips, emails or usernames unless you do it on the VPS or something. Another extra thing I want to be added, is to add the function for add MBs of ram and disk when creating a server because 1GB is so much to be the min. percentaje.

**Comment by camwhi-te** [comment]
This is better done via an external system such as Cloudflare, this won't be directly implemented. Thanks for suggesting this, though.
