### ISSUE TITLE
Shut down all servers on a node

### ISSUE THREAD

**Issue by BasToTheMax** [Jexactyl/Jexactyl#148]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When you need to do a emergency maintenance, it would be nice to be able to stop all running severs on that node.

### Additional context to this request.

Keep it simple

**Comment by camwhi-te** [comment]
Already a thing: https://pterodactyl.io/community/tutorials/artisan.html#server-bulk-power

**Comment by babyharpsea** [comment]
Or just do:
cd /var/lib/pterodactyl/volumes && docker container stop * && systemctl disable --now docker

Whenever you're done:
systemctl enable --now docker
