### ISSUE TITLE
Sidebar not loading in phone on admin panel

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#152]
### Current Behavior

Basically the sidebar in the admin panel doesn't show up in phone.

### Expected Behavior

Supposed to show the sidebar.

### Steps to Reproduce

1. Login to your admin account using a phone
2. Go to the admin panel

### Panel Version

3.4.4

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
A temporary workaround for this is to use your phone in landscape mode

**Comment by heyitslumi** [comment]
> A temporary workaround for this is to use your phone in landscape mode

i actually had to enable desktop mode lmfao

**Comment by OlekAleksander** [comment]
@cmrxnn ?

**Comment by Groot239** [comment]
@cmrxnn really need it it irritates to go in desktop mode it also misclicks on desktop mode

**Comment by camwhi-te** [comment]
It will be fixed when it is fixed.

**Comment by camwhi-te** [comment]
Closing for v4
