### ISSUE TITLE
Allow automatic allocation creator to assign IP alias/hostname automatically

### ISSUE THREAD

**Issue by ItzExotical** [Jexactyl/Jexactyl#153]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I think that there should be an option here that allows you to set an IP Alias/hostname to automatically assign to the created allocations.
![brave_y85Nybr9BP](https://user-images.githubusercontent.com/93738720/194723102-276389b5-b972-4398-9689-e70dae51b2ec.png)

### Additional context to this request.

Nope.

**Comment by camwhi-te** [comment]
This would have to be done per-node which makes it quite complex. You're welcome to make a feature request for Pterodactyl to implement this, but sadly I will not.
