### ISSUE TITLE
Anti-fraud measure for renewals

### ISSUE THREAD

**Issue by ItzExotical** [Jexactyl/Jexactyl#155]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Right now the panel allows anyone to delete their service and get their resources refunded. However, really hungry people will probably delete their server 1 day before it's due, get their resources back, and create a new server. There should be a limit on how many times someone can delete their servers.

### Additional context to this request.

Nope.

**Comment by camwhi-te** [comment]
This is intentional, the loss to the user is the files in which they had on their server and the configuration they had set up for it.
