### ISSUE TITLE
Error when trying to add resources to server

### ISSUE THREAD

**Issue by ItzExotical** [Jexactyl/Jexactyl#156]
### Current Behavior

When one of my customers tries to add more resources to his server (in this case CPU power), he gets the error in the image below. He has enough CPU power in his resource bank to be able to upgrade it.
![unknown](https://user-images.githubusercontent.com/93738720/194727636-019c6c24-dc01-4d13-81b8-4a61a8176346.png)

### Expected Behavior

The panel should add 50% CPU power to his server.

### Steps to Reproduce

1. Go to any server you own created with credits.
2. Go to the "Edit" tab.
3. Try to add more CPU power (I think it is the same with all of them, but still). Make sure to have 50% CPU power in the resource bank.
The error occurs after the above steps.

### Panel Version

3.4.4

### Wings Version

1.7.2

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
https://bin.ptdl.co/apace/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Resolved in 7a7256705dd63d4ac641e08a2a6d950a1675ecc6

**Comment by camwhi-te** [comment]
This error is still occuring and therefore the issue has been reopened
