### ISSUE TITLE
Changing the currency changes back to EUR

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#157]
### Current Behavior

I don't think this is an issue with everyone but changing to some currency's changes back to EUR.

### Expected Behavior

Supposed to change the currency we choosed (like GBP)

### Steps to Reproduce

1. Go to the admin panel
2. Go to the storefront and change the currency to anything random (like GBP)

### Panel Version

3.4.4

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Unable to reproduce

**Comment by NotJag** [comment]
Getting this same issue, fresh installation.
