### ISSUE TITLE
Add a popup to setup a account in Discord 

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#158]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When creating an account using Discord, you don't have a option to put a password when creating an account. For example, your Discord account gets hacked and you don't want to go through the process of resetting your password (even tho you never set a password).

**Comment by heyitslumi** [comment]
update: you can't even access SFTP without a password

**Comment by camwhi-te** [comment]
Closing for v4
