### ISSUE TITLE
be able to customize the main color of the panel and be able to change the login image to your logo

### ISSUE THREAD

**Issue by philip44373** [Jexactyl/Jexactyl#159]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

so the main color is green and it would be cool if we can customize that in the dashboard as well as be able to change the login image to your logo

**Comment by OlekAleksander** [comment]
already a thing, change the logo om the admin area and change the color pallete in the tailwind config file

**Comment by philip44373** [comment]
1. the logo on the admin area does not change in login page
2. i already tried it and i cant find a grren color plus you will need to change it from other things too this is why i want this

**Comment by camwhi-te** [comment]
This will not be implemented, people have the ability to make themes for Jexactyl
