### ISSUE TITLE
MCPASTE button

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#16]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A button to send the logs to mcpaste

### Describe the solution you'd like.

A button in console that uploads all of the logs to mcpaste

**Comment by camwhi-te** [comment]
Resolved in 29c9070dbd13cb74d11a673e0e336f90ef8d68b6
