### ISSUE TITLE
Easier way to add server components.

### ISSUE THREAD

**Issue by RedWolf246** [Jexactyl/Jexactyl#162]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would suggest that you make it easier to upgrade components (upgrade RAM, CPU, …) cause ata this time, I can’t find anything about how to add for example RAM.

**Comment by camwhi-te** [comment]
This is available in the 'Edit' tab which can be found in the server navigation bar
