### ISSUE TITLE
Not showing database tab

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#163]
### Current Behavior

After adding the database, there is still no database tab in the server settings
![IMG_20221026_100044](https://user-images.githubusercontent.com/113983409/197963942-3cb86548-4cda-4932-902b-4aa023aefc6b.jpg)
![IMG_20221026_100127](https://user-images.githubusercontent.com/113983409/197963950-2d18a81f-c796-481b-a249-521271932090.jpg)

### Expected Behavior

Create database in server settings

### Steps to Reproduce

Go to server > click on database tab and create server (but here no button tab Databases)

### Panel Version

3.5.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

No respone

### Docker Image

No response

### Error Logs

```bash
No response
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
I believe this only affects the mobile navigation, but this shall be fixed with the next release.

**Comment by camwhi-te** [comment]
@HalmenNime Are you able to confirm that this is *only* an issue on mobile devices? This should not occur on desktops (or with desktop mode enabled in your browser).

**Comment by HalmenNime** [comment]
>
> @HalmenNime Are you able to confirm that this is _only_ an issue on mobile devices? This should not occur on desktops (or with desktop mode enabled in your browser).

I tried from a computer, still there is no database tab

**Comment by HalmenNime** [comment]
@cmrxnn 
I'm not on the desktop right now, but I'll take a screenshot from the gif from issue #165, it shows that there is a menu bar but there is no database tab
![IMG_20221027_122228](https://user-images.githubusercontent.com/113983409/198246716-be1344bb-9fa1-4606-ae7c-09a5c90702b4.jpg)

**Comment by HalmenNime** [comment]
@cmrxnn 
Bug very strange but i find small fix, I have now created a database in one of my servers manually through the admin panel and right there in other servers the database tab appeared
