### ISSUE TITLE
No test and saving mail settings

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#164]
### Current Behavior

Mail settings not saving after click save or test
![IMG_20221026_103059](https://user-images.githubusercontent.com/113983409/197967743-6c66fa4c-9f76-4c0f-9ff3-fab154e3a3f3.jpg)

### Expected Behavior

Test and save mail settings for use

### Steps to Reproduce

Go to admin panel > mail > fill fields > try test and save

### Panel Version

3.5.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

No response 

### Docker Image

No response

### Error Logs

```bash
No response
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
i have a simmilar issue.

**Comment by TheFallenSpirit** [comment]
I had this same issue, had to manually set all the values in the environment config.

**Comment by philip44373** [comment]
same issue had to go to .env and change it from there

**Comment by Radiant1106** [comment]
My test email works but when I click on "Forgot Passwword" then mail does not got sent.
