### ISSUE TITLE
Can't delete server

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#165]
### Current Behavior

Can't delete server in server settings
![b1Dd4Ok9EI](https://user-images.githubusercontent.com/113983409/197984757-28dcda6b-4ce6-4351-8baa-7c029c4a3af5.gif)

### Expected Behavior

The server will be deleted

### Steps to Reproduce

Select server > go to tab "Settings" > try delete server

### Panel Version

3.5.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

No respone

### Docker Image

No response

### Error Logs

```bash
No response
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
Is the node up?

**Comment by HalmenNime** [comment]
> Is the node up?

Yes, node online and work

**Comment by HalmenNime** [comment]
Here is what I get in the browser console
![image](https://user-images.githubusercontent.com/113983409/198065329-e07c1ceb-ab9d-4c10-92ad-bdd1aa15f0e3.png)

**Comment by camwhi-te** [comment]
Able to reproduce, marking as high priority, will be fixed within the day
