### ISSUE TITLE
Problem with approval system

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#166]
### Current Behavior

When approval system enabled, no one can't register account because of this, with disabled approval system good work
**Webhook URL correct**

![unknown](https://user-images.githubusercontent.com/113983409/198046259-12c923b8-9b2c-4439-97f1-351d04239f3a.png)

_this email just created for test, don't try to spam it's useless_

### Expected Behavior

When someone registers an account, the webhook will send to the channel and say about it for approval

### Steps to Reproduce

SignUp with email > fill fields > click register

### Panel Version

3.5.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

No response 

### Docker Image

No response

### Error Logs

```bash
http://bin.ptdl.co/gihjb

Error 500 in browser console after click register
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Thanks for providing all of the necessary information, it is extremely helpful. This will be marked as high priority and shall likely be fixed within 24 hours. 👍🏼
