### ISSUE TITLE
Problem with add/change additional language and name language

### ISSUE THREAD

**Issue by HalmenNime** [Jexactyl/Jexactyl#167]
### Current Behavior

I have 2 problems with this
1. When you select a language and click "Update User", it shows an error 500
![IMG_20221027_125608](https://user-images.githubusercontent.com/113983409/198257175-0445aba3-b1ed-46c9-8421-5bca272e1022.jpg)
![IMG_20221027_131009](https://user-images.githubusercontent.com/113983409/198257409-64edb9ed-23f6-4add-b121-7d2e04cac7aa.jpg)

2. UA is defined as empty, i think will be good to add in list and name this to "Українська"
![IMG_20221027_131329](https://user-images.githubusercontent.com/113983409/198258782-1896c234-006f-4134-8ceb-b2aa420a925f.jpg)
![IMG_20221027_125744](https://user-images.githubusercontent.com/113983409/198258786-39420ce8-25fe-4fb5-8a18-3bc4a8eecbf4.jpg)

### Expected Behavior

the language will change to what was changed in the ru and ua folders and will show the translated texts from those folders

### Steps to Reproduce

Admin panel > users > select user > try change language for user

### Panel Version

3.5.0

### Wings Version

1.7.0

### Games and/or Eggs Affected

No response 

### Docker Image

No response

### Error Logs

```bash
http://bin.ptdl.co/2ravr
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by HalmenNime** [comment]
Additional information: when you try to change language and update user and get error 500, it automatically changes back to English

**Comment by camwhi-te** [comment]
Am I right in saying this is a modification you've made to the Panel?

**Comment by cmrxnn** [comment]
Am I right in saying this is a modification you've made to the Panel?

**Comment by cmrxnn** [comment]
Am I right in saying this is a modification you've made to the Panel?

**Comment by HalmenNime** [comment]
> 
I don’t know how to say for sure, I just copied the en folder and pasted it, renamed it to ru and ua, and in the admin panel there is an item that you can change the language for the user

**Comment by HalmenNime** [comment]
> Am I right in saying this is a modification you've made to the Panel?

I don’t know how to say for sure, I just copied the en folder and pasted it, renamed it to ru and ua, and in the admin panel there is an item that you can change the language for the user

**Comment by camwhi-te** [comment]
The language feature for Pterodactyl doesn't currently work (to my knowledge) therefore I'm closing this issue for now.
