### ISSUE TITLE
Scroll to botton button is too big

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#17]
### Current Behavior

![IMG_20220618_214452](https://user-images.githubusercontent.com/66617078/174455068-652216c5-7e47-471a-a102-127f4170eed6.jpg)

### Expected Behavior

The button to be at the left bottom, not as big.

### Steps to Reproduce

Run a server and scroll to top

### Panel Version

3.0.1

### Wings Version

1.6.1

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
also the icon doesnt really fit with the other ones*

**Comment by camwhi-te** [comment]
I'll probably just outright remove this feature, as it's just a nuisance and doesn't work 90% of the time from my personal experience.

**Comment by camwhi-te** [comment]
Resolved in 485bfd27c62d9489de7213a73d0038efde150972
