### ISSUE TITLE
Problem with user deletation server

### ISSUE THREAD

**Issue by FungY911** [Jexactyl/Jexactyl#170]
### Current Behavior

![image](https://user-images.githubusercontent.com/74965749/198583845-2c037907-27f7-498e-a9b6-d947fd60a4eb.png)

### Expected Behavior

delete server

### Steps to Reproduce

in server > id > settings > Delete Server

### Panel Version

3.5.0

### Wings Version

1.7.2

### Games and/or Eggs Affected

Discord (Python)

### Docker Image

ghcr.io/software-noob/pterodactyl-images:python_2.7

### Error Logs

```bash
http://bin.ptdl.co/j5pvc
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Resolved, will be fixed for v3.5.1
