### ISSUE TITLE
Registration/Referrals Broken

### ISSUE THREAD

**Issue by WinterFe** [Jexactyl/Jexactyl#174]
### Current Behavior

Refer to #106 

![image](https://user-images.githubusercontent.com/42700057/199864290-451afa68-cda1-4891-b0b3-1650d4b2ed21.png)
![image](https://user-images.githubusercontent.com/42700057/199872027-8eeec707-02e4-4996-ba90-022c9ba6c46c.png)

https://panel.lunardev.group/api/client/account/referrals - 500
### Expected Behavior

Registration to complete.
Referrals to load/work

https://panel.lunardev.group/api/client/account/referrals - Return 200 or data

### Steps to Reproduce

Migrated from Pterodactyl to Jexactyl.

Register with either email or Discord OAuth.
GET https://<domain>/api/client/account/referrals

### Panel Version

3.5.0

### Wings Version

1.7.2

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
https://bin.ptdl.co/zrx8v/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Kilemsam** [comment]
Approved system bug reported in #166
Referral system bug already reported in #169

Don't duplicate issues and check other issues for such a problem

**Comment by WinterFe** [comment]
> Approved system bug reported in #166 Referral system bug already reported in #169
> 
> Don't duplicate issues and check other issues for such a problem

these were closed and marked as completed/fixed. Though, they clearly are not. This was tested on canary and latest

**Comment by Kilemsam** [comment]
> > Approved system bug reported in #166 Referral system bug already reported in #169
> > Don't duplicate issues and check other issues for such a problem
> 
> these were closed and marked as completed/fixed. 

> > Approved system bug reported in #166 Referral system bug already reported in #169
> > Don't duplicate issues and check other issues for such a problem
> 
> these were closed and marked as completed/fixed. Though, they clearly are not. This was tested on canary and latest

Where this canary, I see only last it's develop branch

**Comment by camwhi-te** [comment]
Reference my previous comment on your other issue.
