### ISSUE TITLE
Renew Schedule

### ISSUE THREAD

**Issue by WinterFe** [Jexactyl/Jexactyl#178]
### Current Behavior

The renewals feature isn't subtracting a day after 24h with renewals enabled.

![image](https://user-images.githubusercontent.com/42700057/200158447-a7504d4c-f285-4d8a-bb1f-4a26fe8f7814.png)

This renewal date has been 30d for about 3 days now.

### Expected Behavior

The renewal command to run properly every 24h

### Steps to Reproduce

Full installation of Jexactyl, enable renewals, wait 24h

### Panel Version

3.5.0

### Wings Version

1.7.2

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
https://pteropaste.com/o95cq1/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by FungY911** [comment]
Same
