### ISSUE TITLE
Customizable max resources for a server

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#18]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

There should be an option to limit the max ram,cpu,disk for a server.

### Describe the solution you'd like.

A section in storefront settings.

**Comment by camwhi-te** [comment]
Resolved in 488627ad550f9e8b7c685a7a56349317201ab051
