### ISSUE TITLE
Approve all

### ISSUE THREAD

**Issue by FlameCafe** [Jexactyl/Jexactyl#182]
### Current Behavior

When I click "Approve All" I get a 500 error

### Expected Behavior

I expected for it to be a successful on all approval

### Steps to Reproduce

When I click on my approval system there was like over 5 approvals and then I clicked on "Approval All" then a white page popped up with the 500-page error

### Panel Version

3.5.1

### Wings Version

1.7.2

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
Error 500
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by FungY911** [comment]
its fixed

**Comment by camwhi-te** [comment]
"I have searched the existing issues before opening this issue."

Please actually only tick this checkbox if you really have looked.
This is fixed for `v3.6`.
