### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by FungY911** [Jexactyl/Jexactyl#183]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

- Referrals Logs for Admins
- Buy quantity in store
- toggle order resources & create server to MB/GB
- See user referrals in **admin/users** 
- Move **enter referral code** From **/account** to **account/referrals**
- add coins to **store/resources**
- ticket system
- Vouchers
- role with permissions assign

**Comment by camwhi-te** [comment]
This is not how to format issues
