### ISSUE TITLE
Change currency to 'credits' in suspended screen block

### ISSUE THREAD

**Issue by FungY911** [Jexactyl/Jexactyl#184]
https://github.com/Jexactyl/Jexactyl/blob/1f862e71f25540458b407f424c3d279818fed72d/resources/scripts/components/elements/Suspended.tsx#L76

- fix {store.currency} to **coins**

**Comment by babyharpsea** [comment]
Pretty sure is fine, you don't want it to be **150 2593**, which is what would say if you changed store.currency,
Even though I may be wrong, please correct me if needed.

**Comment by FungY911** [comment]
No, its not correct becose you dont pay money for reneval but you pay coins.
