### ISSUE TITLE
Activity log transformer error

### ISSUE THREAD

**Issue by ElDaterXD** [Jexactyl/Jexactyl#185]
### Current Behavior

When I put a webhook in the user approval section I get the error 500 server error

### Expected Behavior

Don't know

### Steps to Reproduce

enter the admin panel, user approvals and enter a webhook

### Panel Version

3.5.1

### Wings Version

1.7.2

### Error Logs

```bash
https://pteropaste.com/7vl25i/
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Unable to reproduce this issue on v3.5.1
