### ISSUE TITLE
Credit Card/Bank (Payment Gateway)

### ISSUE THREAD

**Issue by bitUpsurge** [Jexactyl/Jexactyl#186]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

There should be an option to easily implement Payment method of Credit Card and Bank using our Bank in which we have a account without third party controllers like stripe.

**Comment by camwhi-te** [comment]
This is exactly what Stripe is

**Comment by bitUpsurge** [comment]
Stripe is not available in every country.

**Comment by bitUpsurge** [comment]
Manual integration will be perfect in such scenarios.

**Comment by bitUpsurge** [comment]
@cmrxnn
