### ISSUE TITLE
Unable to create subusers

### ISSUE THREAD

**Issue by ThePolishLemon** [Jexactyl/Jexactyl#187]
### Current Behavior

![image](https://user-images.githubusercontent.com/82435316/202902576-c4439f60-d536-472a-9529-bb0aeeba1e2f.png)

Shows this error while trying to add a subuser

### Expected Behavior

Accualy add the subuser

### Steps to Reproduce

Go to the users tab from the server view and try to invite a user

### Panel Version

3.5.1

### Wings Version

1.7.2

### Games and/or Eggs Affected

All

### Error Logs

```bash
https://bin.ptdl.co/n4unn/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ThePolishLemon** [comment]
Also wanna add tht i tested it on 2 seprate jexactyl instances both of whitch showed the issue

**Comment by OlekAleksander** [comment]
I have a simmilar problem too.
No logs.

**Comment by camwhi-te** [comment]
Logs provided do not show necessary information (for some reason), so I'll do my own research on this

**Comment by camwhi-te** [comment]
@ThePolishLemon You have only uploaded part of the logs, please try to replicate the issue again, send the logs in a commend here, and reopen this issue. This will be closed until reopened by original poster

**Comment by ThePolishLemon** [comment]
Ye im not able to provide any other logs because i've already changed from using jexactyl to pterodactyl because of this issue

**Comment by ThePolishLemon** [comment]
I'll try to make a new test instance l8r 2day to test it tho
