### ISSUE TITLE
Test Mail is working but signups, password resets not working.

### ISSUE THREAD

**Issue by Radiant1106** [Jexactyl/Jexactyl#191]
### Current Behavior

I setuped mail stuff on the panel and when I pressed the test button, the email is being sent from the mail that I setup but when I tried to test forget password stuff then I realised that the system is not sending emails to the email id and I dont know why this is happening even after the test thing works.

### Expected Behavior

I should get email on my account with the new password creation link but I didnt got it.

### Steps to Reproduce

-> I setuped the mail server thing to the panel.
-> I clicked on test button under mail setting in admin settings.
-> The test button said email sent and the email was received.
-> Then I tried logging out of my account and tapping on forget password.
-> I provided my email and presses forget password.
-> System Said that password reset email is sent but I didnt received any email.

### Panel Version

3.5.1

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by WarrioR151** [comment]
Your SMTP setup is bad! There is no problems with email sending!

**Comment by camwhi-te** [comment]
@WarrioR151 Have you tested this yourself? Considering the fact that the test email is working, it's strange that the rest of them aren't in that case. Let me know if things are working for you, and if this is specific to this user.

**Comment by WarrioR151** [comment]
@cmrxnn Yes of course it working fine for me, you also can try on panel.megaplej.eu

**Comment by camwhi-te** [comment]
Closed due to a lack of ability to replicate
