### ISSUE TITLE
Labels for checking minimum resources broken

### ISSUE THREAD

**Issue by AndyIsHereBoi** [Jexactyl/Jexactyl#193]
### Current Behavior

When creating a server it shows minimum 25%,
![image](https://user-images.githubusercontent.com/69745145/203906725-fc597ddf-70a0-4d7f-841f-5e0be038b4aa.png)

 but when I do 25% it will error once more on the server create button showing minimum 50%.
![image](https://user-images.githubusercontent.com/69745145/203906044-e08c618a-fada-4f79-9d06-a5ffc3c34a35.png)

### Expected Behavior

It should be minimum 25% or 50% and them both say the same.

### Steps to Reproduce

create a server with less then 25% cpu set, and this happens

### Panel Version

3.6.0

### Wings Version

1.7.2

### Error Logs

https://pteropaste.com/ckmizr

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
@AndyIsHereBoi What is the 'minimum limit' for CPU set to in the storefront admin settings?

**Comment by AndyIsHereBoi** [comment]
> @AndyIsHereBoi What is the 'minimum limit' for CPU set to in the storefront admin settings?

I do not see a minimum ![Screenshot_20221125-104431.jpg](https://user-images.githubusercontent.com/69745145/204027846-358d7e7c-194f-43e8-ac12-1de5e0b4fe6b.jpg)

**Comment by camwhi-te** [comment]
Fixed for v3.6.1
