### ISSUE TITLE
Per user nodes 

### ISSUE THREAD

**Issue by LegoCraftNW** [Jexactyl/Jexactyl#194]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A group system can be added and selected groups can be authorized to use the desired node. In fact, only the admin and a selected user can access a node.

I want to use it for this purpose: I want the user to be able to manage the server they bought from me with the panel and only have access to its resources.

I want to be able to assign private and public nodes to users.

**Comment by camwhi-te** [comment]
You can accomplish this by setting up a new Panel instance on the server you wish to sell, and adding your client as an administrator on that specific panel.
