### ISSUE TITLE
Create server doesn't work after update

### ISSUE THREAD

**Issue by WarrioR151** [Jexactyl/Jexactyl#195]
### Current Behavior

When i try to create new server, i get error Unable to create this server. Please contact an administrator.
also, sometime if you write less ram etc, it sais Memory must be greater than or equal to 256 on all (256 instead of 4,096 RAM example)

### Expected Behavior

When you press create server it should create server

### Steps to Reproduce

For creation, go to store set it up and click create, error appears and server is not created

For the text bug, go to store set RAM, Disk to for example 4MB, you will see text Memory must be greater than or equal to 256 (this 256 is the bug)

### Panel Version

3.6.0

### Wings Version

1.7.2

### Games and/or Eggs Affected

Minecraft (all, bungee, paper etc)

### Error Logs

```bash
http://bin.ptdl.co/kr8n4
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
Fixed for v3.6.1
