### ISSUE TITLE
Users can't access panel. (timed out) But it works for me

### ISSUE THREAD

**Issue by samhorizon7** [Jexactyl/Jexactyl#196]
![image](https://user-images.githubusercontent.com/84820356/204053338-87fa14d2-d304-4dab-ae84-f162329381f6.png)

**Comment by FungY911** [comment]
error in your server

**Comment by samhorizon7** [comment]
so how do i fix it? be more detailing

**Comment by OlekAleksander** [comment]
First of all, dont use Github Issues for support. Ask for help on jexactyls discord. Also how are we supposed too help you if you didnt send the logs? Have you followed the docs?
