### ISSUE TITLE
Doesn't let you register

### ISSUE THREAD

**Issue by ACGEN9** [Jexactyl/Jexactyl#197]
### Current Behavior

It does not let you register via email, it gives an error

### Expected Behavior

Let new users register

### Steps to Reproduce

When you go to the panel and you are not registered, if you try to register via email, it gives you an error

### Panel Version

lastet

### Wings Version

lastet

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
This has been fixed for the next release.

**Comment by DetectiveNightPrime** [comment]
For the v3.6.0 signup issue (will be fixed within 24h of this message):

In the file app/Http/Controllers/Auth/RegisterController.php
On line 31, under $verified = false;, add:
$prefix = 'jexactyl::registration:';
