### ISSUE TITLE
Save changes button not working

### ISSUE THREAD

**Issue by philip44373** [Jexactyl/Jexactyl#198]
### Current Behavior

when i go to the admin panel and apperance and  do some changes and click the Save changes button it refreshes and says Jexactyl Appearance has been updated.
but no changes are saved

### Expected Behavior

to save the changes

### Steps to Reproduce

make sure to make it change the changes in the database when clicking the button.

### Panel Version

3.6.1

### Wings Version

1.7.3

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed for v3.6.1
