### ISSUE TITLE
Linkvertise coin earning

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#20]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Make an page for earning coins using liknvertise

### Describe the solution you'd like.

A button in the balance tab that redirects the user to an linkvertise tab and give a set amount of coins.

**Comment by ddfsdsfsdf** [comment]
its been 2+ months
