### ISSUE TITLE
Creating a server shows up a error

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#200]
### Current Behavior

When creating a server with 100% CPU or higher, it shows a CPU error and reject creating the server.
![image](https://user-images.githubusercontent.com/94217075/204096727-4f8cdfde-3cc6-4e68-8cb5-1315ed10ac99.png)
![image](https://user-images.githubusercontent.com/94217075/204096729-b8b54d4f-fa93-4711-a537-715ac6c5fbfc.png)

### Expected Behavior

Supposed to create the server with the amount of CPU putted in the storefront.

### Steps to Reproduce

Buy CPU, go to the storefront and try to create a server.

### Panel Version

3.6.1

### Wings Version

1.7.2

### Error Logs

https://bin.ptdl.co/xuen3/ (just changed after creating)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
I am not able to replicate this issue personally.

**Comment by heyitslumi** [comment]
https://cdn.discordapp.com/attachments/1046122560015835356/1046159822892052480/image.png heres another image
sometimes it works sometimes it doesn't

**Comment by heyitslumi** [comment]
useless logs just incase https://bin.ptdl.co/xuen3/
