### ISSUE TITLE
BitPay Integration

### ISSUE THREAD

**Issue by Volas171** [Jexactyl/Jexactyl#207]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Integration with [https://bitpay.com/](https://bitpay.com/) (would pretty much solve anyone suggesting any crypto gateways in a near future.)

**Comment by camwhi-te** [comment]
There's a lot of reasons I won't be integrating this, namely stability of currency, but thanks for the suggestion.
