### ISSUE TITLE
Coupon System

### ISSUE THREAD

**Issue by TheFallenSpirit** [Jexactyl/Jexactyl#208]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A way for admins to create coupons to give to users that will grant a specific amount of credits.
These coupons will have a set expiry time and a max amount of uses. 
Also in the future be able to grant resources to users with the coupons as well.
Possibly a booster coupon that would boost coin earning or decrease resource pricing.

### Additional context to this request.

Please assign this to me @cmrxnn

**Comment by WarrioR151** [comment]
Bump, nice feature

**Comment by maxencefiu** [comment]
+1 great feature too

**Comment by camwhi-te** [comment]
@TheFallenSpirit Status on this?

**Comment by TheFallenSpirit** [comment]
> @TheFallenSpirit Status on this?

About 85% done, just need to finish the frontend.
