### ISSUE TITLE
Load balanced server deployment

### ISSUE THREAD

**Issue by theh2so4** [Jexactyl/Jexactyl#21]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It will be very useful to like:

The node have: 8GB of ram, and 12GB of RWM

- I'm user 1 and I wanna create server X, therefore I create my server with 6GB of ram and 10GB of RWM.
- I'm user 2 and he wanna create server Y, as a result he try to create a server on the same node with 3GB of ram, and 8GB of RWM. But the node can't handle this even tho it has the allocations to do it, therefore server Y is sended to other node in which it can handle the request.

I don't know if I made my self clear, but it would be a very very useful system. I hope it actually gets implemented :)) (Not for next update, but hopefully for the one after this one, or so) - (This + Node selector UI, it can be very top) (IS NOT FREE/PAID NODE, DIFFERENT IDEA)

### Describe the solution you'd like.

I'd like that if node can't handle server Y due to a lack of resources (not allocations, there are allocations but the server is too big to be deployed there, smaller servers can be deployed there, but server X is too big for server Y already), server Y gets deployed in other node.

### Additional context to this request.

It will be actually very useful and unique, is this way people can avoid node overllocation.

**Comment by camwhi-te** [comment]
Resolved in 0544e959ebfc00e4ab98bf7043d53cdb04a39990
