### ISSUE TITLE
Credits Sync

### ISSUE THREAD

**Issue by FungY911** [Jexactyl/Jexactyl#210]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In admin side you can set url and getter name. It will be "sync" with third-party credits.
Link there: **{"coins":15}** i will have now {"coins":**15**} coins and panel will be getting from {"**coins**":15}.

it´s really good for third-party panel

If you somenthing dont understand, just ask.

**Comment by TheFallenSpirit** [comment]
The entire point of Jexactyl is so that you don't need to use third party panels. I don't think this would get implemented tbh as it's not what it's meant to do.

**Comment by FungY911** [comment]
I know, but jexactyl have one payment feature.
