### ISSUE TITLE
Sending credits to other people

### ISSUE THREAD

**Issue by WarrioR151** [Jexactyl/Jexactyl#211]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Sending credits to other people, so when user have credits, there will be button with option to send specified amount to other people, input email, like "Who will receive your credits? Put user email, and amount of credits to transfer" or something.. 

Just sending credits to other people :D

**Comment by TheFallenSpirit** [comment]
I think that this would not be implemented because users could create new accounts and gift themselves resources which would be not good.

**Comment by WarrioR151** [comment]
Ok, So only credits ?

**Comment by WarrioR151** [comment]
Will be good

**Comment by cmrxnn** [comment]
Not being implemented due to TheFallenSpirit's comment
