### ISSUE TITLE
Purchasing resources resets the account's resources to default value

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#212]
### Current Behavior

When buying RAM (or any resources), it resets the RAM set in the admin panel and adds an extra RAM.

### Expected Behavior

Doesn't reset the RAM and adds an extra RAM.

### Steps to Reproduce

1. Enable storefront
2. Set default resources
3. Give yourself more RAM than the ones you set in the admin panel and the amount of credits for 1 RAM
4. Try to buy an extra RAM.

### Panel Version

3.6.2

### Wings Version

1.7.2

### Error Logs

```bash
http://bin.ptdl.co/wfalt
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Volas171** [comment]
This issue has also happened to me, only have been able to reproduce it on android, on pc everything seems to work as it should
### Video of it happening:

https://user-images.githubusercontent.com/60143910/205472489-2c3bf405-a855-4d02-9ad5-b1c5a730e767.mp4

**Comment by camwhi-te** [comment]
@Volas171 Is this only an issue when purchasing memory? Are other resources having the same problem?

**Comment by Volas171** [comment]
> @Volas171 Is this only an issue when purchasing memory? Are other resources having the same problem?

Every other resource seems to be having this bug, users report getting 309% cpu instead of 100%

**Comment by camwhi-te** [comment]
This is genuinely quite strange, I'm not able to reproduce on desktop. Will give it a go in a mobile environment

**Comment by camwhi-te** [comment]
@ItzBenoitXD Can you provide some extra context?

- What platforms does this happen on? (e.g. desktop, mobile etc)
- What resources are affected? (e.g. CPU, RAM etc)

**Comment by vqnish** [comment]
> @ItzBenoitXD Can you provide some extra context?
> 
> * What platforms does this happen on? (e.g. desktop, mobile etc)
> * What resources are affected? (e.g. CPU, RAM etc)

I can help as its also effecting me.

It happens to me on desktop and mobile and also happens to my users. This bug happens to all my resources cpu, ram, disk, ports, backups and databases. People will buy 1gb of ram while having 9gb and instead of them now having 10gb it puts them back at 1 as if its setting the ram as one instead of adding.

**Comment by heyitslumi** [comment]
> @ItzBenoitXD Can you provide some extra context?
> 
>     * What platforms does this happen on? (e.g. desktop, mobile etc)
> 
>     * What resources are affected? (e.g. CPU, RAM etc)

1. It happens on pretty much every platforms.
2. Every resources.

**Comment by camwhi-te** [comment]
@ItzBenoitXD @vqnish @Volas171 Thank you for your help so far. Can everyone please confirm that this issue is still present with v3.6.3? If so, please message me on Discord (Jex#3413). Thanks again

**Comment by iSantiGod** [comment]
The problem is not solved
