### ISSUE TITLE
Email Verification Error

### ISSUE THREAD

**Issue by bitUpsurge** [Jexactyl/Jexactyl#213]
### Current Behavior

Verification email is not being received at the registered account email.

### Expected Behavior

To receive verification email to verify our account.

### Steps to Reproduce

To debug and fix email verification system, it should work as needed.

### Panel Version

3.6.2

### Wings Version

Doesn't require wings

### Error Logs

```bash
http://bin.ptdl.co/tiarl
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheFallenSpirit** [comment]
The logs provided are a MySQL authentication error. Unrelated to the issue mentioned. Make sure you have the cron job setup and enabled as well as the system queue worker.
