### ISSUE TITLE
Enhanced Verification System (Feature Request)

### ISSUE THREAD

**Issue by bitUpsurge** [Jexactyl/Jexactyl#214]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Non verified users should see a warning on dashboard and should be avoided to perform any task before verification and upon visiting profile we should see on it that verify your email, and a button to send a verification email again, it'll make Jexactyl Much Better.

**Comment by TheFallenSpirit** [comment]
It does show a warning if you are unverified. Also you cannot deploy servers unless you are verified and there is a resend button. Could you provide more context to this request?

**Comment by camwhi-te** [comment]
All of this already exists
