### ISSUE TITLE
Panel in the jexactyl that we can choose some eggs to install

### ISSUE THREAD

**Issue by JerComa** [Jexactyl/Jexactyl#216]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Its like a new tab in admin panel, where you can press install egg and it ll be installed into your panel directly

Make this dream tru @jex

**Comment by camwhi-te** [comment]
Use https://github.com/parkervcp/eggs
