### ISSUE TITLE
Prune Command dont giving back resources 

### ISSUE THREAD

**Issue by WarrioR151** [Jexactyl/Jexactyl#217]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi, php artisan p:schedule:prune dont give users their resources back, can you add it So when you delete all expired servers, the resources go back to users account?

**Comment by cmrxnn** [comment]
![image](https://user-images.githubusercontent.com/72230943/205907158-6217beff-9399-4170-8ffe-8d480a4dddea.png)
