### ISSUE TITLE
QIWI Payments

### ISSUE THREAD

**Issue by FantomSmert** [Jexactyl/Jexactyl#219]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

On behalf of all Russian/Belarusian/Ukrainian/I'm telling Kazakh hosting companies, please support the P2P QIWI payment system or something similar.

API https://developer.qiwi.com/en/p2p-payments/

**Comment by camwhi-te** [comment]
Sticking with PayPal and Stripe for now
