### ISSUE TITLE
Renew Whitelist

### ISSUE THREAD

**Issue by theh2so4** [Jexactyl/Jexactyl#22]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Like a whitelist, if you whitelist a user from server renewal, all of users servers will be renewed automatically by Jexactyl.

### Describe the solution you'd like.

I will like to have like a part on the admin panel where you can whitelist users from the server renewal.

### Additional context to this request.

This is useful for Staff, and it will be very useful to have an endpoint.

**Comment by camwhi-te** [comment]
Servers created via the admin pages are exempt from renewals, but servers created via the Jexactyl Storefront are renewable. I'll make a toggle for this in the admin menu, thanks for the suggestion.

**Comment by theh2so4** [comment]
Is there going to be an endpoint in the API?

**Comment by camwhi-te** [comment]
Potentially, it'll probably just be incorporated into the existing PATCH route for servers.
