### ISSUE TITLE
Ticket Support System

### ISSUE THREAD

**Issue by 0TIME0** [Jexactyl/Jexactyl#220]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add a Ticket System to Jexactxl would be awesome for Hosting company's.

**Comment by ghost** [comment]
+1 i totally agree to add this feature!

**Comment by maxencefiu** [comment]
+1 great idea bro

**Comment by camwhi-te** [comment]
Completed for v3.7.0
