### ISSUE TITLE
SMTP issue in new update

### ISSUE THREAD

**Issue by SharmaStudios** [Jexactyl/Jexactyl#221]
### Current Behavior

I tried to use SMTP it works in old version but in new version it doesn't work

### Expected Behavior

For SMTP to work in new update

### Steps to Reproduce

Idk

### Panel Version

3.6.3

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by DarkShoro** [comment]
Not a valid bug report, no logs whatsoever and step to reproduce aren't given, please try to see if it's on your side as their is nothing that I know about that could cause this issue.

**Comment by SharmaStudios** [comment]
No error logs

**Comment by camwhi-te** [comment]
Fixed for the next release, refer to latest GitHub commit
