### ISSUE TITLE
Fix the way to get unlimited coins

### ISSUE THREAD

**Issue by Ansh8915** [Jexactyl/Jexactyl#223]
### Current Behavior

There is a bug in Jexactyl which allows user to get unlimited coins please fix ASAP!

### Expected Behavior

People Can use it to abuse hosting coins and it can badly affect them

### Steps to Reproduce

IDK

### Panel Version

3.0.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
1. Your not even running the latest version so it's probably patched
2. Does Jexactyl even support Wings 1.4.2?
3. If you can send us error logs, maybe Jex can fix it.

**Comment by camwhi-te** [comment]
You provided no reproduction steps, no logs, and you're running a much older version. Please update to the latest release.
