### ISSUE TITLE
Password reset email not sending

### ISSUE THREAD

**Issue by jvvan** [Jexactyl/Jexactyl#225]
### Current Behavior

When you request a password reset, it doesn't send the email. In activity logs it shows that it was requested, but the email is never sent.

### Expected Behavior

Email should be sent properly.

### Steps to Reproduce

Go to login page
Click forgot password
Enter email and submit
No mail comes

### Panel Version

3.6.2

### Wings Version

1.11.0

### Error Logs

There are no logs related to this.

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by devnote-dev** [comment]
Related: pterodactyl/panel#4604

**Comment by camwhi-te** [comment]
^ This has been resolved for the next release.
