### ISSUE TITLE
Default Resources Update

### ISSUE THREAD

**Issue by theh2so4** [Jexactyl/Jexactyl#23]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

When you actually change the default resources once users are registered, the resources doesn't update for users that are registered already.

### Describe the solution you'd like.

Default Resources update once is changed from the setting, even for registered users.

**Comment by camwhi-te** [comment]
This is deliberate, it would be a royal pain to propagate this across every user on the DB.
