### ISSUE TITLE
Installation broken

### ISSUE THREAD

**Issue by lis0** [Jexactyl/Jexactyl#231]
### Current Behavior

After installation of Jexactyl some things (I checked only admin panel) don't work like /admin/nodes

### Expected Behavior

To work

### Steps to Reproduce

1. Install pterodactyl
2. Install jexactyl

### Panel Version

3.6.3

### Wings Version

not working

### Error Logs

```bash
file not found
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
You will need to provide a lot more information in order for me to verify this. Namely panel/browser logs as well as more detailed reproduction steps.

If you're using Cloudflare's proxy, that's probably why.
