### ISSUE TITLE
Ad a subdomain manager

### ISSUE THREAD

**Issue by r4club** [Jexactyl/Jexactyl#232]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The user can create up to || select in the admin area || subdomains per server.

**Comment by OlekAleksander** [comment]
This most likely wont be added as there is already an addon for that.

**Comment by OlekAleksander** [comment]
But we'll see

**Comment by camwhi-te** [comment]
Not going to be added as upstream will be working on this. It'll be pulled if/when they complete it.
