### ISSUE TITLE
Adding Subuser Not Working 

### ISSUE THREAD

**Issue by BossDevlopment** [Jexactyl/Jexactyl#233]
### Current Behavior

When Ever I Try To Add Subuser It Shows Error

### Expected Behavior

#
![Uploading Screenshot_20221218-054313_Chrome.jpg…]()

### Steps to Reproduce

Solve This

### Panel Version

3.6.3

### Wings Version

1.11.2

### Error Logs

```bash
https://pteropaste.com/84ifj8
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
please include steps to reproduce on how to do it cause i can't replicate this issue

**Comment by camwhi-te** [comment]
Logs are not relevant and no repro steps provided, closing
