### ISSUE TITLE
Backups can't be added

### ISSUE THREAD

**Issue by WarrioR151** [Jexactyl/Jexactyl#234]
### Current Behavior

When user want to add backup (with edit button) it writes "You cannot add this resource because an administrator has set a maximum limit." but actually my limit is 2, and he have 0 backups

### Expected Behavior

When you click on add backup in edit tab, that should give you + one more backup for your server

### Steps to Reproduce

Buy backup slot, create a server (with backup 0 so you can match the limit of 1) in server press Edit, add backup, you get error

### Panel Version

3.6.3

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
Fixed for the next release
