### ISSUE TITLE
New Payments brazil

### ISSUE THREAD

**Issue by joinasau** [Jexactyl/Jexactyl#237]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello, I'm from Brazil and I'm having problems with paypal, could you add a Brazilian payment method, in this case: "Mercado Pago". api: https://www.mercadopago.com.br/ferramentas-para-vender/cobrar?utm_experiment=optimize&matt_tool=79642323&matt_word=MLB_MP_G_AO_OP_COW_BRAND_SELL_CONV_TRANPARENTE&gclid=Cj0KCQiA-oqdBhDfARIsAO0TrGGtoFBJMYmx-yrLjxsdzfac9i-3yhBjt30dWGK4xEc0msSWDTmLqtIaAu91EALw_wcB

**Comment by camwhi-te** [comment]
Please refer to my comment in the #github channel
