### ISSUE TITLE
php artisan p:schedule:prune not working

### ISSUE THREAD

**Issue by philip44373** [Jexactyl/Jexactyl#238]
### Current Behavior

php artisan p:schedule:prune is supposed to delete all suspended servers I ran the command and I got 
Running server prune...
Processing renewals for 0 servers.
Script completed successfully.
even tho I have over 150 suspended servers.

### Expected Behavior

Delete all suspended servers.

### Steps to Reproduce

Having suspended servers and run this command php artisan p:schedule:prune and servers will not get deleted.

### Panel Version

3.6.3

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
had used the prune command and it works

**Comment by camwhi-te** [comment]
Can confirm that the script still works as intended

**Comment by philip44373** [comment]
I tried it on 2 different panels and its the same issue made my friend try it and same thing.
