### ISSUE TITLE
Official addon support

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#24]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A way to upload addons for the panel, without modifying the panel itself.

### Describe the solution you'd like.

A folder in the panel files for addons. Maybe an addon store.

**Comment by camwhi-te** [comment]
Considering the fact that there are already features that can be controlled via the admin menus, it doesn't make much sense for there to be an addon store - they can just be directly baked into the panel.
