### ISSUE TITLE
Minimum gets changed randomly 

### ISSUE THREAD

**Issue by SharmaStudios** [Jexactyl/Jexactyl#244]
### Current Behavior

When select 20 says 25 and when do 30 days 50 please fix this issue 

### Expected Behavior

Both should be same

### Steps to Reproduce

Create a server shows error 

### Panel Version

3.7.0

### Wings Version

1.7.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
This is not an issue with the Panel

**Comment by SharmaStudios** [comment]
The panel forces to give 100% cpu
