### ISSUE TITLE
Ticket Notifications

### ISSUE THREAD

**Issue by SharmaStudios** [Jexactyl/Jexactyl#245]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to l see if some one creates ticket we don't know when he created it's just abandoned so i want there should be a information pop up that there is one ticket pending and it will only show to admins

**Comment by OlekAleksander** [comment]
Another cool thing that you might add are email notifications.

**Comment by Ashu11-A** [comment]
A Webhooks of this for Discord would be great

**Comment by camwhi-te** [comment]
This feature exists for v4, closing
