### ISSUE TITLE
Allocation Status

### ISSUE THREAD

**Issue by Hazza3100** [Jexactyl/Jexactyl#246]
### Current Behavior

Underneath each allocation Alias it has a spinning recycle like it's not working.

### Expected Behavior

It should be a tick or green heart something along these lines.

### Steps to Reproduce

Change status of Alias.

### Panel Version

3.7.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
why are you running a old version of wings

**Comment by camwhi-te** [comment]
@ItzBenoitXD Wings ver is irrelevant in this specific issue

**Comment by Hazza3100** [comment]
> why are you running a old version of wings

I'm not I just didn't change it from the prompted version.
