### ISSUE TITLE
In main menu "Your Servers" doesn't update

### ISSUE THREAD

**Issue by greysilly7** [Jexactyl/Jexactyl#247]
### Current Behavior

When you switch between your servers and others servers the "Your Servers" text stays the same

### Expected Behavior

To switch between "Your Servers" and "Others Servers'

### Steps to Reproduce

1. Switch between yours and others servers 

### Panel Version

3.7.0

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Resolved in #252
