### ISSUE TITLE
Discord ID has already been taken error

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#249]
### Current Behavior

When you try to do like any action (for example creating a server), it still does the action but it will also show a error saying that the Discord ID has already been taken like in the screenshot.
![image-18](https://user-images.githubusercontent.com/94217075/210268456-f6688827-9cf2-4699-9c93-0dbaf95845a8.png)

### Expected Behavior

It's supposed to not show any errors and do the action.

### Steps to Reproduce

I randomly got this issue so I can't really explain but if I'm correct, you need to create a user using Discord.

### Panel Version

3.7.0

### Wings Version

1.11.0

### Error Logs

```bash
http://bin.ptdl.co/baddt
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
`discord_id` is a unique property and here it seems you have two accounts with the same Discord ID which is not intended. This issue is showing up because the User model is being updated and will not allow the `discord_id` field to be changed as it is already unique to another account.

Will take a look at this soon

**Comment by heyitslumi** [comment]
> `discord_id` is a unique property and here it seems you have two accounts with the same Discord ID which is not intended. This issue is showing up because the User model is being updated and will not allow the `discord_id` field to be changed as it is already unique to another account.
> 
> Will take a look at this soon

welp my IQ is now low

**Comment by camwhi-te** [comment]
Closing this due to it being an extremely low use-case and user error
