### ISSUE TITLE
Some pull requests from pterodactyls github

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#25]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

https://github.com/pterodactyl/panel/pull/4132 - Popout Console
https://github.com/pterodactyl/panel/pull/3900 - Select all permissions button
https://github.com/pterodactyl/panel/pull/3821 - File sorting in file manager

### Describe the solution you'd like.

Add this features

**Comment by camwhi-te** [comment]
Top two have been implemented, bottom PR will not be as there is already a file search bar.
