### ISSUE TITLE
Change "Tickets" to a help page

### ISSUE THREAD

**Issue by ItzExotical** [Jexactyl/Jexactyl#254]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I think the "Tickets" page should be renamed to "Help" or "Support" and then there should be tabs like "Tickets", "Knowledge base" (or "FAQ"), and possibly a "Network status" (or "Uptime") page too. That way the customers won't contact support about common issues that can be resolved easily with a knowledge base. Jexactyl already replaces WHMCS and other billing systems pretty well, but if it should be able to do that fully there should be a support system like that. 

### Additional context to this request.

None.

**Comment by camwhi-te** [comment]
The spacing issue has been resolved for the next release, but what tabs should go at the top?

**Comment by ItzExotical** [comment]
@cmrxnn Changed to a feature request. Please re-check the original comment.

**Comment by camwhi-te** [comment]
I'm going to settle for a middle-ground and allow admins to set links which point to external status pages, knowledge bases etc

**Comment by Ashu11-A** [comment]
Up

**Comment by camwhi-te** [comment]
Closing as this can be done via very simple modifications. Does not seem to me that it must be implemented on every panel instance. Good suggestion, but I won't be implementing it due to this. Thanks
