### ISSUE TITLE
Block Certain Email Providers 

### ISSUE THREAD

**Issue by Person0z** [Jexactyl/Jexactyl#258]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Could yall add an ability in the ```admin>settings``` to block certain email domains from signing up on the panel? Like people sign up with temp emails and I really don't want to allow that. Or whitelist emails too so only like ```gmail, outlook, hotmail, yahoo``` and other major email providers are able to sign up and all other ones are blocked with a message showing "this domain prover has been blocked, please use another email"

**Comment by camwhi-te** [comment]
You are able to delete users with certain emails. You could set up a cronjob to do this and therefore it won't be implemented in the Panel (yet) - Thanks for the suggestion though.
