### ISSUE TITLE
Add something new xD

### ISSUE THREAD

**Issue by ProsameYT** [Jexactyl/Jexactyl#261]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

This can help host owner control better for host!

### Additional context to this request.

Add: Staff permissions
add: Suspended options,we can suspend account if she/he breaks host terms who not allow login panel! + when account get suspend server get suspend to!
Add: im not sure if this working,but can you make,we can choice what nodes he can make that server?
example: i have node: bedrock,java,proxy, and is nest: java,bedrock,proxy we can allow only java nest to make server only on java xD

**Comment by camwhi-te** [comment]
This is not how you format an issue. The only feature I would consider implementing is the user suspension system, which you are welcome to make a new issue for.
