### ISSUE TITLE
Plugin Manager is intermittently not working

### ISSUE THREAD

**Issue by camwhi-te** [Jexactyl/Jexactyl#262]
### Current Behavior

There are occasions where the plugin manager (on develop branch) is having some issues. I believe it is working in the latest stable release and if anyone can confirm that, that'd be great.

### Expected Behavior

Plugin manager should display a list of plugins

### Steps to Reproduce

- Go to Plugin Manager on any server
- Type in a search query
- See error

### Panel Version

develop

### Wings Version

N/A

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Skipsqueak514** [comment]
I believe this is a feature, according to jex he only creates these types of features not "bugs" and yes hello Jex i know that is you.

**Comment by Skipsqueak514** [comment]
yes this needs to be fixed.

**Comment by camwhi-te** [comment]
@Skipsqueak514 Precisely why I made an issue for it...

**Comment by camwhi-te** [comment]
Closed in latest commit
