### ISSUE TITLE
Add a Verify Email button

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#263]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It might be useful for some people that receive the verify email to the spams folder while the other emails goes to the inbox folder.

### Additional context to this request.

I know this won't be added as almost no one has this issue and that I can't explain properly but let's just wait.

**Comment by camwhi-te** [comment]
This already exists, and will not disappear until the user has been verified.

**Comment by WarrioR151** [comment]
But verification system Don't work for long time Now, Its like the Burton in admin settings does nothing, doesnt matter if verify Is enabled or disabled, it dont take effect,
