### ISSUE TITLE
First node dont change eggs

### ISSUE THREAD

**Issue by WarrioR151** [Jexactyl/Jexactyl#270]
### Current Behavior

https://youtu.be/ahp_TEluk-4

### Expected Behavior

When you set default nest to private, and another to public it should normally show the nest's eggs, no the default one

### Steps to Reproduce

Set default nest with ID 1 to private, set another nest to public, go to store, and you see in nest is your choosen nest, but in eggs you still see default eggs from default nest 1

### Panel Version

3.7.0

### Wings Version

1.11.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
This has been fixed for the next release
