### ISSUE TITLE
Email Verification is not working

### ISSUE THREAD

**Issue by dftzippo** [Jexactyl/Jexactyl#271]
I have a problem when users register through the Jexactyl panel, the "Created Account" email arrives, but the "Email Verification" email is not sent and the function is active.

* The SMTP configuration is correctly configured, otherwise the "Created Account" email would not arrive.

* The email from "Email Verification" is also not in the Spam folder.

![Picsart_23-01-30_08-40-20-804](https://user-images.githubusercontent.com/80356208/215531067-96ac9348-3c24-4378-bb62-86fe0b99c47a.jpg)
![Picsart_23-01-30_08-40-46-360](https://user-images.githubusercontent.com/80356208/215531075-95e9cf22-7ba7-416b-9406-ef34a490d752.jpg)

**Comment by camwhi-te** [comment]
Please check the queue worker logs:

`systemctl status panel`

**Comment by heyitslumi** [comment]
fallen made a working fix so here it is if you need it: https://discord.com/channels/922284031129825280/1034612251908395049/1046494332275929088

**Comment by Groot239** [comment]
@cmrxnn same issue with me
