### ISSUE TITLE
Send notifications to users via email a notification center in the dashboard 

### ISSUE THREAD

**Issue by dftzippo** [Jexactyl/Jexactyl#272]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I would like to see a feature added to be able to notify certain users or all users via email or have a notification center in the dashboard where administrators can send notifications to certain users or to all users.

### Additional context to this request.

* Sorry if you didn't understand me, I'm using a translator :)

**Comment by camwhi-te** [comment]
It's a nice idea but there is not much use for this, as the whole point is that users are emailed.
