### ISSUE TITLE
Remove suspended server after X days

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#275]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Auto remove a suspended (not renewed) server after X days.

### Additional context to this request.

It would be easier for hosting owners to manage suspended servers.

**Comment by camwhi-te** [comment]
`0 0 * * * php /var/www/jexactyl/artisan p:schedule:prune`

**Comment by OlekAleksander** [comment]
I know but i want it to show on the panel, with days remaining. I can do it myself, but i thought this would be a good feature.

**Comment by Skipsqueak514** [comment]
a placeholder you mean?

**Comment by OlekAleksander** [comment]
Kind of.
