### ISSUE TITLE
"The Steam Account Token variable field is required.

### ISSUE THREAD

**Issue by username-98** [Jexactyl/Jexactyl#277]
### Current Behavior

when clients select to deploy a csgo server, the panel replies ""The Steam Account Token variable field is required." but i dont see any field input for the steam account token" 

same for deploy "custom sourcegame" but with diffrent error,this one replies "game id field required" but there is no field to input the game id on the panel,

### Expected Behavior

select csgo server, a new field appears to put the steam token code data
or 
select custom sourcegame and a new field appears to put the sourcegame game id

### Steps to Reproduce

.

### Panel Version

3.0.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Set the field as 'nullable' in egg settings, and then set it when the server has been created.
