### ISSUE TITLE
500 SERVER ERROR in Tickets (admin area)

### ISSUE THREAD

**Issue by officialszcz** [Jexactyl/Jexactyl#279]
### Current Behavior

Hello! I have a problem with my panel, when i go to tickets in client area it works perfectly fine but when i go to tickets in admin area i got 500 SERVER ERROR
![image](https://user-images.githubusercontent.com/85417714/225580913-f7377c86-c16f-4ebf-8caf-55f06fe390e8.png)
![image](https://user-images.githubusercontent.com/85417714/225580990-931a3d60-6143-4d34-bbbc-7efebff5e6a3.png)

### Expected Behavior

I want to get a solution how to repair this.

### Steps to Reproduce

When i go to /admin/tickets i got 500 error

### Panel Version

3.7.0

### Wings Version

1.11.4

### Error Logs

```bash
Panel: https://pteropaste.com/cslmv2iw95zv/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by tahaluindo** [comment]
how to fix 503
SERVICE UNAVAILABLE

**Comment by KiroFyzu** [comment]
> how to fix 503 SERVICE UNAVAILABLE

you can use this `$ php artisan up`
**Possible**
