### ISSUE TITLE
Crypto payment

### ISSUE THREAD

**Issue by devil38** [Jexactyl/Jexactyl#28]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Support for Coingate

### Describe the solution you'd like.

Adding support for crypto payments would be a good idea

**Comment by DemonMartin** [comment]
Support for Binance & KuCoin would be cool too

**Comment by Shillerman2022** [comment]
🌴 incomeisland metaverse🌴
👉Ca renounced
👉Metaverse beta live
👉3D property staking
👉Team KYCd
👉Darcy donavan CoOwner
👉Random Burn
$INCOME
🌴Tokenomics
2% LP
2% BNB rewards
6% Marketing

**Comment by camwhi-te** [comment]
Not going to support this after consideration. Sorry, Crypto lovers.
