### ISSUE TITLE
Automatic Task When Create Specific Type Of Server

### ISSUE THREAD

**Issue by kvfs2k07** [Jexactyl/Jexactyl#281]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

I'd like a new tab inside the egg install script than can pre-configure tasks and make it unremovable from the task section. Like falixnodes: when you make a Minecraft Server, when it detects no one in the server, starts a countdown of 1 hour and if anyone joins the server is shut down. 

### Additional context to this request.

I don't mean that it can detect players in a minecraft server and something like that. I suggest a tab where you can make tasks before the server is made.

**Comment by Ashu11-A** [comment]
I think this is too complicated, why don't you use an Egg already made for this: https://github.com/QuintenQVD0/Q_eggs
![image](https://user-images.githubusercontent.com/30575805/228679727-ffe6bb30-13f5-4793-8969-9ac18abf93e5.png)

**Comment by camwhi-te** [comment]
Refer to above comment
