### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by kvfs2k07** [Jexactyl/Jexactyl#282]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

New tab inside server where you can do something like replit's secrets variable

**Comment by Ashu11-A** [comment]
if that's it, up
![show-secrets](https://user-images.githubusercontent.com/30575805/228680653-d14fc505-9470-4114-b53b-299cfe396212.gif)

**Comment by camwhi-te** [comment]
You can set env vars in many ways, such as using a dotenv or modifying the startup command. It's a nice idea but not worth implementing at this time.
