### ISSUE TITLE
Not A Issue Just Looking For Support

### ISSUE THREAD

**Issue by zachary435** [Jexactyl/Jexactyl#284]
Hello I want to add an extra button onto the sidebar of jexactyl 

this is the code I added

				{phpmyadmin && (
                    <NavLink to={'google.com'} className={'navigation-link'}>
                        <Tooltip placement={'bottom'} content={'PHPMyAdmin'}>
                            <div className={'bg-gray-700 rounded-lg p-2 my-8'}>
                                <Icon.ShoppingCart size={32} />
                            </div>
                        </Tooltip>
                    </NavLink>
                )}

however it doesn't show up can I get some advice

**Comment by OakleyCord** [comment]
Not a great place to look for support, ask the help channel instead on the discord (https://discord.com/invite/qttGR4Z5Pk), also you should probably provide what file you changed and where.

**Comment by camwhi-te** [comment]
Refer to message above
