### ISSUE TITLE
Allow admins to create gift cards which members can claim

### ISSUE THREAD

**Issue by cashlycash** [Jexactyl/Jexactyl#285]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

- A clear way to create a gift card which can be claimed by anyone when used.
- The gift card can be set by any string which can be set manually or can be auto generated as well.
- Once the gift card will be used it will be shown on the admin portal that it was used by this specific person and that gift card will no longer work.
- The ability to use it multiple times by different people only should exist as well.
- The gift card will be disabled only not deleted after use so that it can be seen who all used it. (there will be a button to delete it as well).

**Comment by Skipsqueak514** [comment]
+1

**Comment by camwhi-te** [comment]
A 'coupon' system has already been implemented on `develop` and will be introduced with the next major version release. Great suggestion but @TheFallenSpirit beat you to it! :)
