### ISSUE TITLE
Use vite and pnpm

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#286]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Pterodactyl has already done that for v2 a while ago. It improves the speed of compiling and makes the life easier for developers.

**Comment by camwhi-te** [comment]
Not planning on doing this due to it requiring a massive rewrite of code structure - Vite will likely come in the future but it is not planned for now. This will be reopened when the time comes
