### ISSUE TITLE
Better edit screen

### ISSUE THREAD

**Issue by starrider346** [Jexactyl/Jexactyl#288]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The current tab to edit server resources isn’t the best with just the + and - buttons. Maybe it could be sliders then the person presses a confirm button once they have made the edits.

If this isn’t possible, even some text on each saying how much it has would be good.

**Comment by Vaultpls** [comment]
I agree on adding what the server currently has assigned to it as well if sliders aren't part of the UI flow.  Blindly pressing the + and - button is a bit user unfriendly when you can't see what you're modifying.

**Comment by camwhi-te** [comment]
Closing for v4
