### ISSUE TITLE
Server creation egg selection shows eggs from wrong nest

### ISSUE THREAD

**Issue by starrider346** [Jexactyl/Jexactyl#289]
### Current Behavior

I had all the nests except 2 custom nests I made. When you open the server creation UI, the selected nest is the first of the 2 public nests but the egg selection is from the default Minecraft nest until you change nest selection and it updates itself.

### Expected Behavior

The egg selection should be the selected nest.

### Steps to Reproduce

Hide all existing nests.
Create a new nest with some eggs.
Open the server creation ui.

### Panel Version

3.7.0

### Wings Version

1.11.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
Question: Why are you using a old version?

**Comment by starrider346** [comment]
I meant 3.7.0. Sorry

**Comment by camwhi-te** [comment]
This should be fixed in the latest version. If it's not, feel free to re-open.
