### ISSUE TITLE
auto installer for versions of Jexactly like pterodactyl

### ISSUE THREAD

**Issue by KiroFyzu** [Jexactyl/Jexactyl#290]
### Is there an existing feature request for this?

- [ ] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

bash <(curl -s https://pterodactyl-installer.se)
to
bash <(curl -s https://jexactyl-installer.se)

🗿🗿

**Comment by gOOvER** [comment]
in my eyes Not needed an this Installer make more problems than its helpfull

**Comment by heyitslumi** [comment]
very useless suggestion not gonna lie

**Comment by ThePolishLemon** [comment]
least useless suggestion in ohio
