### ISSUE TITLE
Nest creation error

### ISSUE THREAD

**Issue by securing-ab** [Jexactyl/Jexactyl#296]
### Current Behavior

When I press on "Save" while creating a new nest, the panel throws a 500 error

### Expected Behavior

Create the nest

### Steps to Reproduce

Try to create a nest

### Panel Version

3.7.1

### Wings Version

1.11.6

### Error Logs

```bash
http://bin.ptdl.co/l94gv
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [x] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
This seems to be an issue with the egg you are using. Try adding an "author" field to the JSON file near the top and see if that fixes your error.

This has been tested with several eggs from `parkervcp/eggs`
