### ISSUE TITLE
admin page 500 error

### ISSUE THREAD

**Issue by Shirobaka** [Jexactyl/Jexactyl#297]
### Current Behavior

After Update to latest version i get 500 Error when opening Admin Panel

### Expected Behavior

Admin Panel should work

### Steps to Reproduce

Open Admin Panel

### Panel Version

3.7.1

### Wings Version

1.11.6

### Error Logs

```bash
http://bin.ptdl.co/dizcr
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed for next version

**Comment by Shirobaka** [comment]
Still not working
`https://bin.ptdl.co/ilia8/`
