### ISSUE TITLE
Webhooks for ticket

### ISSUE THREAD

**Issue by naysakiu** [Jexactyl/Jexactyl#298]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hi 

As a hosting provider some customers are creating ticket on the game panel , and it will be nice if to add a optional webhook for tickets, which will send a message on a discord server for ticket creation , reply etc

**Comment by camwhi-te** [comment]
Duplicate of #245
