### ISSUE TITLE
Error while creating account

### ISSUE THREAD

**Issue by Antoniovbn000** [Jexactyl/Jexactyl#3]
### Current Behavior

When you click create an account it will show Unable to create account, but your account will work

### Expected Behavior

Expected behavior its not to show error

### Steps to Reproduce

![slika](https://user-images.githubusercontent.com/63794922/173437284-13dc8617-18a5-41cb-b700-e022fe728db0.png)

### Panel Version

3.0.0

### Wings Version

1.6.4

### Games and/or Eggs Affected

/

### Docker Image

/

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Able to reproduce

**Comment by OlekAleksander** [comment]
Able to reproduce too.
