### ISSUE TITLE
Auto-Deploy Failure

### ISSUE THREAD

**Issue by PenguCCN** [Jexactyl/Jexactyl#30]
### Current Behavior

After grabbing the auto-deploy code and pasting it we've been getting this error: authentication credentials provided were not valid. All keys work properly except for deploying nodes
![image](https://user-images.githubusercontent.com/86432003/175765985-1e961fa0-fc33-4c5a-b4f4-f43c5f1b71f3.png)

### Expected Behavior

Expected: Accepted keys and configuration file created

### Steps to Reproduce

Upgrade from Pterodactyl to Jexactyl, attempt to deploy a node using the Node-Deployer
![image](https://user-images.githubusercontent.com/86432003/175766011-078b9223-5667-430f-938e-78284d87a29b.png)

### Panel Version

3.1.1

### Wings Version

1.6.4

### Error Logs

```bash
https://bin.ptdl.co/b2qkk/
```

### Is there an existing issue for this?

- [x] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheFallenSpirit** [comment]
Reading through the error logs provided this is a DNS resolution failure. This is not an issue with Jexactyl.
