### ISSUE TITLE
server past renewal date

### ISSUE THREAD

**Issue by Aidenw210** [Jexactyl/Jexactyl#303]
### Current Behavior

i have a friend who is running a test server on my panel but i had a look and the server is past renewal but nothing has happened. i have enabled the renewal system.
![image](https://github.com/Jexactyl/Jexactyl/assets/58526185/43f90f3a-ac29-40ba-8551-63c2345bcaac)
![image](https://github.com/Jexactyl/Jexactyl/assets/58526185/3f6331e9-1b3e-4116-88ff-aab42a85483d)
![image](https://github.com/Jexactyl/Jexactyl/assets/58526185/71e4ed37-602f-47c0-8e81-ef24c4133dad)

### Expected Behavior

server stops and isn't allowed on till the server renewal is paid

### Steps to Reproduce

i used other servers on other accounts and still not working

### Panel Version

3.7.2

### Wings Version

1.4.2

### Games and/or Eggs Affected

none

### Docker Image

Not egg specific

### Error Logs

```bash
https://ptero.co/ejodihekod
https://pteropaste.com/ammt6sq7mwg3
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OakleyCord** [comment]
did you make sure the cronjob for renewals is running?

**Comment by camwhi-te** [comment]
I'll put this through further testing but assume worst-case scenario for now and set the bug to high priority assuming this can be replicated.

**Comment by HaseoTM** [comment]
I do not believe this to be a bug, I had this same issue earlier this week. My renewals were not working and I found out it was because inside my crontab I had the path incorrect. IF you migrated from pterodactyl the name will be /var/www/pterodactyl/artisan and NOT /var/www/jexactyl/artisan

**Comment by camwhi-te** [comment]
I'm not able to replicate this either. Closing
