### ISSUE TITLE
Coupon system bug

### ISSUE THREAD

**Issue by ShadowPro1** [Jexactyl/Jexactyl#305]
### Current Behavior

You can keep claiming the coupon on the same user for infinite ammount of times

### Expected Behavior

You should have been let to reedem it only once

### Steps to Reproduce

Make a coupon with more than 2 uses and reedem it

### Panel Version

 v3.7.2

### Wings Version

1.11.6

### Error Logs

```bash
http://bin.ptdl.co/ypfex
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Skipsqueak514** [comment]
Quote from Fallen, "Whenever a coupon it uses it removes one from the "uses" column until that column is less then 1 in an integer format so it then disables that coupon
If you want many uses then set it to like 99999"

**Comment by camwhi-te** [comment]
I'll do some research. Can't confirm the severity of this at the moment but it'll most likely be addressed in the next release.

**Comment by camwhi-te** [comment]
Closing for v4
