### ISSUE TITLE
admin page 500 error (Still not fixed)

### ISSUE THREAD

**Issue by Shirobaka** [Jexactyl/Jexactyl#307]
### Current Behavior

After Update to latest version i get 500 Error when opening Admin Panel
(Same as in #297 - still not fixed)

### Expected Behavior

Admin Panel should work

### Steps to Reproduce

Open Admin Panel

### Panel Version

3.7.2

### Wings Version

1.11.6

### Error Logs

```bash
https://bin.ptdl.co/370t7/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
You need to set up your web server permissions.

**Comment by Shirobaka** [comment]
> You need to set up your web server permissions.

I already did that multiple times, it doesn't fix the problem.

**Comment by camwhi-te** [comment]
This seems like a configuration error - I can see the panel is not being hosted from a typical directory. Try installing Jexactyl on a base Debian/Ubuntu install, following the install guide correctly, and see if the issue persists.
