### ISSUE TITLE
Node Issue

### ISSUE THREAD

**Issue by xlelordsOntop** [Jexactyl/Jexactyl#311]
### Current Behavior

When u go to the node section it says 500 server error

### Expected Behavior

supposed to show all the nodes

### Steps to Reproduce

it instantly brings to a 500 server error page

### Panel Version

3.7.2

### Wings Version

1.11.6

### Games and/or Eggs Affected

None

### Docker Image

None

### Error Logs

```bash
500 server error
```

### Is there an existing issue for this?

- [ ] I have searched the existing issues before opening this issue.
- [ ] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [ ] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by ItzBenoitXD** [comment]
logs will definitely help us

**Comment by xlelordsOntop** [comment]
there is no logs it just says 500 server error

**Comment by ItzBenoitXD** [comment]
> there is no logs it just says 500 server error
> 

have you even executed the command to generate logs

**Comment by Skipsqueak514** [comment]
give logs...

**Comment by xlelordsOntop** [comment]
there was no log and i fixed the issue some reason the node files were deleted some reason
