### ISSUE TITLE
Sub Domain Manager

### ISSUE THREAD

**Issue by Marios1111** [Jexactyl/Jexactyl#312]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Be able to let the user connect his cloudflare and use his domain for the hosting.

**Comment by pcking99** [comment]
Good idea but cloudflare requires a paid plan to let others point their domains to your ip that you might have in cloudflare.

**Comment by ayu2606** [comment]
> Good idea but cloudflare requires a paid plan to let others point their domains to your ip that you might have in cloudflare.

Nope it does not.

**Comment by ayu2606** [comment]
> Good idea but cloudflare requires a paid plan to let others point their domains to your ip that you might have in cloudflare.

Nope it does not.

**Comment by ayu2606** [comment]
> ### Is there an existing feature request for this?
> * [x]  I have searched the existing issues before opening this feature request.
> 
> ### Describe the feature you would like to see.
> Be able to let the user connect his cloudflare and use his domain for the hosting.
> 
> ### Additional context to this request.
> _No response_

Upstream will get this update in v2
