### ISSUE TITLE
Too many attempts

### ISSUE THREAD

**Issue by adr-1an** [Jexactyl/Jexactyl#315]
### Current Behavior

When I try creating a new server from the store, it says "Too many attempts" in red.
![image](https://github.com/Jexactyl/Jexactyl/assets/104342201/9e88f4b6-b47f-4180-a4ca-c4b50d2b5f83)

### Expected Behavior

I should be able to create a server normally, with no errors.

### Steps to Reproduce

Try creating a server from the store.

### Panel Version

3.7.2

### Wings Version

1.11.6

### Error Logs

```bash
http://bin.ptdl.co/hgl0o
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by kitzurea** [comment]
I am also having this issue, some help would be great!

**Comment by camwhi-te** [comment]
This is fixed for the next release
