### ISSUE TITLE
Footer Credits - Jexactyl Built On Jexactyl

### ISSUE THREAD

**Issue by TheGamer3514** [Jexactyl/Jexactyl#316]
### Current Behavior

![image](https://github.com/Jexactyl/Jexactyl/assets/79448904/68320004-41a1-4b77-97ba-ec30ee1cd579)
Footer says Jexactyl Built On Jexactyl

### Expected Behavior

Footer to say Jexactyl Built On Pterodactyl

### Steps to Reproduce

look at footer credits

### Panel Version

3.7.2

### Wings Version

1.11.6

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in next release
