### ISSUE TITLE
Egg Import Design Error

### ISSUE THREAD

**Issue by Panda260** [Jexactyl/Jexactyl#317]
### Current Behavior

[Image](https://img.neverstopgaming.net/Panda/chrome_OdUVayjKCA.png)

Cant select the Nest when trying to import an egg

### Expected Behavior

[Image](https://img.neverstopgaming.net/Panda/chrome_HcXbpzWAGB.png)

### Steps to Reproduce

was already like that after the installation

### Panel Version

3.7.2

### Wings Version

1.11.6

### Games and/or Eggs Affected

no

### Docker Image

no

### Error Logs

```bash
https://ptero.co/hibydolily
https://bin.ptdl.co/i62i4/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by OlekAleksander** [comment]
What browser are you using?

**Comment by Panda260** [comment]
Chrome in Edge is no design glitsch only in Chrome

**Comment by camwhi-te** [comment]
Closing for v4
