### ISSUE TITLE
Force deleting a server returns 500 error when Wings is offline

### ISSUE THREAD

**Issue by zymsbgt** [Jexactyl/Jexactyl#318]
### Current Behavior

Panel returns a 500 server error page

### Expected Behavior

Server successfully force deletes the server from the panel

### Steps to Reproduce

1. Go to a server hosted on a node where Wings is offline
2. Go to Delete > Force Delete Server

### Panel Version

3.7.2

### Wings Version

unavailable (the node hosting the affected server has been removed)

### Error Logs

```bash
https://bin.ptdl.co/625vv/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
This seems to be linked to a panel-side database connection issue rather than a bug with the code. If more error logs can be provided with different exceptions that'd be great, but for right now it looks like that's a configuration issue.

**Comment by zymsbgt** [comment]
Sorry I'm 3 weeks late to reply, but you please elaborate on how is this a configuration issue, and what error logs would be good to have? I've just looked through my panel and database configuration and it all looks good
