### ISSUE TITLE
Adding miner detector

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#32]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The panel should detect miners automatically if someone uploads miners' files or runs miners in the panel and then suspend the server with the reason by informing about it in the admin tab.

### Describe the solution you'd like.

I could like to see when the server gets suspended then there we should be required to provide a reason for suspending it. And there should be a miner detector implemented in the panel so it will detect miners and suspend its servers by informing admins about it in the admin tab.

**Comment by OlekAleksander** [comment]
Hard to detect

**Comment by ghost** [comment]
> Hard to detect

Not that hard. I already make a miner detector but I code it in python and used API for it to get server details and all.

**Comment by camwhi-te** [comment]
No real way of doing this and preventing workarounds. Not something we're going to support.
