### ISSUE TITLE
Uncaught Stripe Exceptions

### ISSUE THREAD

**Issue by devnote-dev** [Jexactyl/Jexactyl#320]
### Current Behavior

(ref: [Discord](https://discord.com/channels/922284031129825280/1034612251908395049/1123280705493946440))

Making purchases via Stripe can cause a 500 error response from the panel if the Stripe configuration is invalid (for example, an invalid `APP_URL` value in the `.env` file).

### Expected Behavior

Stripe exceptions should be caught and displayed to the user.

### Steps to Reproduce

1. [Setup the Stripe integration](https://docs.jexactyl.com/#/latest/payments/stripe)
2. Set the `APP_URL` variable to an invalid domain/URL
3. Attempt to make a payment in the panel using Stripe

### Panel Version

3.7.2

### Wings Version

1.11.6

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
Unavailable.
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Closing for v4
