### ISSUE TITLE
Credit AFK earning not working

### ISSUE THREAD

**Issue by GreenFruit1** [Jexactyl/Jexactyl#321]
### Current Behavior

The users dont get credits to their account, but they get greeted with a    POST https://panel.skycastle.us/api/client/store/earn 500
bundle.4f2b9e97.js:1 Failed to add credits error (error code 500)

### Expected Behavior

Users getting credits

### Steps to Reproduce

Happened randomly

### Panel Version

3.7.2

### Wings Version

1.11.6

### Games and/or Eggs Affected

N/A

### Docker Image

N/A

### Error Logs

```bash
https://pteropaste.com/r26fkrq7w34h/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Assuming this is reproducible for now, this will be set to high priority.

**Comment by camwhi-te** [comment]
AFK coin earning is working on develop, so if it's broken in the current release it will be fixed in the next.
