### ISSUE TITLE
Skrill support

### ISSUE THREAD

**Issue by adr-1an** [Jexactyl/Jexactyl#322]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add Skrill support so you can buy credits directly through Skrill.

**Comment by TheGamer3514** [comment]
![image](https://github.com/Jexactyl/Jexactyl/assets/79448904/577a2d6b-2a89-4f49-b66b-59570dc8ede5)

**Comment by adr-1an** [comment]
Oh alr, sorry
