### ISSUE TITLE
Log file took up 500 GB

### ISSUE THREAD

**Issue by TenDivnej** [Jexactyl/Jexactyl#328]
### Current Behavior

I left a server running overnight which is needed becuase it needs to stay up 24/7... and i came back this morning to a 500 internal error, which was cause by not having enough space on a disc and i wondered why, because it was weird. and when i conducted a search i found that it was a log file of a server which had 500+GB 
![WinSCP_OgN7M4KhZG](https://github.com/Jexactyl/Jexactyl/assets/142686366/792a78fd-9b17-4949-80f9-1e3a75551ea4)

I dont know what caused this, but i resolved it by deleting the log file for now, if it happens again i dont know what is causing it!

i am using the standart egg for a minecraft server.

**_I AM WRITING THIS JUST TO MAKE ANYONE AWARE OF THAT THIS CAN HAPPEN_**

### Expected Behavior

not creating a log file that is 500+GB

### Steps to Reproduce

as i said i dont know how this happened, server was on only about 12 hours at that time, then panel and everything gave up because lack of storage

### Panel Version

3.7.2

### Wings Version

1.11.7

### Games and/or Eggs Affected

Minecraft (Paper)

### Docker Image

ghcr.io/pterodactyl/yolks:java_17

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by heyitslumi** [comment]
this issue can be closed as
1. it's not a jexactyl issue
2. there's a plugin / mod / something that is generating all the logs which is not usually normal
3. if you can, delete some of your plugins since your amount of plugins... It's using 1 GB
4. this is not a permanent suggestion but why do you need to leave it 24/7?

**Comment by TenDivnej** [comment]
ok, and i need to leave it 24/7 because there are people playing on it from different countries, which have different timezones. so thats why it needs to run 24/7. and as i said this is "issue" is just to make people aware that this can happen...

**Comment by heyitslumi** [comment]
> ok, and i need to leave it 24/7 because there are people playing on it from different countries, which have different timezones. so thats why it needs to run 24/7. and as i said this is "issue" is just to make people aware that this can happen...

it doesn't usually happen on production uses also I would use lazymc if I was you but your choice

**Comment by camwhi-te** [comment]
This isn't an issue with Jexactyl but is an issue with the software you're running. I'd recommend maybe setting a schedule to delete logs every X minutes, or removing plugins which consistently spit errors or logs.
