### ISSUE TITLE
[DockerPanel] - AdvancedSetting not used

### ISSUE THREAD

**Issue by ItJustFox** [Jexactyl/Jexactyl#329]
### Current Behavior

The setting inside Advanced is not being used, and act like if there is nothing in the database while there is the setting I set.

(Typically, 2Factor is on `2` at database but `Notrequired` inside the panel)
![image](https://github.com/Jexactyl/Jexactyl/assets/42358087/b927dcf2-881d-4523-80a9-009feb781fc1)
![image](https://github.com/Jexactyl/Jexactyl/assets/42358087/aa5ed2ef-a1bc-4f7b-a800-f7412ebeb2ef)

### Expected Behavior

Setting being used on the right way, and the fact that the 2Factpr authentification force all user has accepted to set it up... while actually he doesn't care

### Steps to Reproduce

Install the Pterodactly Panel on docker version
Then install Jexactyl above (You can use this script I made for auto update.)
```
apk add bash
curl https://install.kalifondation.fr/ptero/jexactyl.sh --output panelupdate.sh && bash panelupdate.sh
```

### Panel Version

3.7.2

### Wings Version

1.11.7

### Games and/or Eggs Affected

Panel Docker

### Docker Image

ghcr.io/pterodactyl/panel:latest

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by zvikasdongre** [comment]
Fixed in https://github.com/Jexactyl/Jexactyl/pull/326
