### ISSUE TITLE
Purchaseable server plans

### ISSUE THREAD

**Issue by Juice2007** [Jexactyl/Jexactyl#33]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

To be able to sell pre-made servers and to be able to disable and enable products on the shop page. The hosting service should be able to get receive a monthly payment from each user.  Also to buy ram and other stuff and when making servers they pay monthly. 

### Describe the solution you'd like.

A billing page and a better shop page maybe.

**Comment by camwhi-te** [comment]
Marked as `low priority` as it's quite a significant change which won't be introduced very soon.

**Comment by camwhi-te** [comment]
Closed due to the nature of Jexactyl's billing system. It's meant to be a PAYG system, however, you can create renewals so users must pay x credits per x days in order to keep their server active, making it more subscription-y.
