### ISSUE TITLE
Broken Mobile UI

### ISSUE THREAD

**Issue by mambucodev** [Jexactyl/Jexactyl#332]
### Current Behavior

The servers in the list are not displayed on mobile view, there's just thin rectangles with the running/starting/stopped colored dot on the right.

### Expected Behavior

The servers should display name, address:port and resources if running.

### Steps to Reproduce

Open the Jexactyl panel from mobile view, logged in.

### Panel Version

3.7.3

### Wings Version

1.11.6 and 1.11.8 (two nodes)

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by WifiRouterYT** [comment]
Having the same issue.
![image](https://github.com/Jexactyl/Jexactyl/assets/45213292/fba3fe0e-48e6-4d59-951c-810b4f269f03)

**Comment by ghost** [comment]
Having the same issue x2
![image](https://github.com/Jexactyl/Jexactyl/assets/120841550/ecc4fea9-cb9a-451c-99fd-7f3fa100fbcc)

**Comment by renerettig** [comment]
I can confirm this issue being present for me too

**Comment by kokofixcomputers** [comment]
Can confirm. Trying to work on a fix.

**Comment by kokofixcomputers** [comment]
I fixed it! https://github.com/kokofixcomputers/Jexactyl

**Comment by kokofixcomputers** [comment]
Please note that if you update to my repo, There is many other fixes, things. So.... if you **JUST** want this one fixed, don't update it.

Although I think no one will hate these features :)

**Comment by camwhi-te** [comment]
@kokofixcomputers Would you be able to make a PR? If not I'm happy to take the code manually from the repo (if you're okay with that)?

**Comment by kokofixcomputers** [comment]
> @kokofixcomputers Would you be able to make a PR? If not I'm happy to take the code manually from the repo (if you're okay with that)?

Sure, I will. I just need to create a new branch with the changes then I can just merge that change. I will do that.

**Comment by kokofixcomputers** [comment]
@camw0 I created a pull request: https://github.com/Jexactyl/Jexactyl/pull/353

**Comment by camwhi-te** [comment]
Closing for v4
