### ISSUE TITLE
Egg import UI bug

### ISSUE THREAD

**Issue by G0nter** [Jexactyl/Jexactyl#334]
### Current Behavior

<html>
<body>

Daemon Version | 1.11.8 (Latest: 1.11.8)
-- | --
System Information | Linux (amd64) 5.15.0-88-generic

</body>
</html>

![image](https://github.com/Jexactyl/Jexactyl/assets/61696125/619133fa-2697-43d0-9c5f-b5e60c745598)

### Expected Behavior

Simply when you want to import an egg to a category, it does not clear the category list, which prevents you from being able to import it correctly.

### Steps to Reproduce

Simply when you want to import an egg to a category, it does not clear the category list, which prevents you from being able to import it correctly.

### Panel Version

3.7.3

### Wings Version

1.11.8

### Error Logs

```bash
Wings: https://ptero.co/ucowujured
Panel: http://bin.ptdl.co/b3sd5
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by smashyalts** [comment]
had same issue, fixed it by using Firefox instead of chrome

**Comment by G0nter** [comment]
I also have the same problem from the phone, should I use another browser as well?
To be honest, it's a bug that should be fixed.

**Comment by camwhi-te** [comment]
Closing for v4
