### ISSUE TITLE
Unable to unlink Discord account from profile.

### ISSUE THREAD

**Issue by WifiRouterYT** [Jexactyl/Jexactyl#335]
### Current Behavior

When trying to unlink a discord account from the Account page, the console throws a 500 error and does not unlink the Discord account.
![Screenshot 2023-11-25 at 11 01 07 PM](https://github.com/Jexactyl/Jexactyl/assets/45213292/d436dc90-90a0-41e7-b268-4aef727a1995)

### Expected Behavior

The discord account should be unlinked with no errors.

### Steps to Reproduce

1. Link a Discord account or register with Discord to a Jexactyl panel
2. Go to your account settings and make sure you're in Account Overview
3. Open up your browser's developer console and hit this button:
![image](https://github.com/Jexactyl/Jexactyl/assets/45213292/bda053a2-55c8-410b-ae76-19216435d98a)
4. Nothing will happen on the site, however in the browser console you will see a 500 (Internal server error) error. https://http.cat/500

### Panel Version

3.7.3

### Wings Version

1.11.6 (Latest: 1.11.8)

### Error Logs

originally none, was caused by permission errors however.
with error:
https://pteropaste.com/ociyetat6xrd

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [x] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Noritem** [comment]
i have this to

**Comment by TheGamer3514** [comment]
This was fixed in #348
