### ISSUE TITLE
Cannot authenticate with discord

### ISSUE THREAD

**Issue by adambotfd** [Jexactyl/Jexactyl#336]
### Current Behavior

Shows a blank page after signin

### Expected Behavior

Authenticate with discord

### Steps to Reproduce

Login with discord

### Panel Version

3.7.3

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheGamer3514** [comment]
Works completely fine for me and my users. Probably an issue with your config somewhere

**Comment by SexyEis** [comment]
Its bugged if you have 2FA eneabled on your Discord acc. I have the same issue but someone else without 2FA has tested with 2 accounts with no 2FA and no problems there

**Comment by TheGamer3514** [comment]
> Its bugged if you have 2FA eneabled on your Discord acc. I have the same issue but someone else without 2FA has tested with 2 accounts with no 2FA and no problems there

I have my discord and panel account with 2fa. Works fine, all my accounts work fine

**Comment by smashyalts** [comment]
having same issue with my users, only happening to new panel users it looks like?

**Comment by camwhi-te** [comment]
This will happen if the email already exists on the system. That in itself needs to be fixed, but Discord authentication itself is working.
