### ISSUE TITLE
Add a way to modify coupons and delete them.

### ISSUE THREAD

**Issue by heyitslumi** [Jexactyl/Jexactyl#337]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

There would be on the right side of the coupons list, buttons for example, modify or delete coupons. It will solve a issue with users having to go to MySQL just to delete a coupon, which I find it pretty risky. [jex being lazy real](https://discord.com/channels/922284031129825280/1034612251908395049/1180318296113946656)

**Comment by heyitslumi** [comment]
update: I'm blind to lemme fix this real quick

**Comment by camwhi-te** [comment]
Closing for v4
