### ISSUE TITLE
stripe multiple payment methods

### ISSUE THREAD

**Issue by LouisBeke** [Jexactyl/Jexactyl#338]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

stripe multiple payment methods,
like iDeal, Klarna, etc 
![payment-element](https://github.com/Jexactyl/Jexactyl/assets/142576734/e1cb55b9-5fe3-42ce-8fb8-d5e9a4d7b247)

**Comment by camwhi-te** [comment]
This would be something you can configure on Stripe's end.
