### ISSUE TITLE
Plugin installer

### ISSUE THREAD

**Issue by JamieGrimwood** [Jexactyl/Jexactyl#34]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Install plugins via a tab to install plugins onto the server (IF ENABLED ON THE EGG, as you don't want a plugin installer on a discord.js egg)

### Describe the solution you'd like.

To be able to download plugins from the panel

**Comment by babyharpsea** [comment]
There are already several addons for that, hence it'll result in a loss for the addon authors:

https://pterodactylmarket.com/resource/406
https://pterodactylmarket.com/resource/142

**Comment by camwhi-te** [comment]
Jexactyl's implementation will be much simpler and less feature-rich than addons that are available. It won't be designed to knock paid systems out of the park, but it will just be a simple yet beneficial addition to the Panel.

**Comment by camwhi-te** [comment]
Resolved in b7d1dd2fd7a666c1ada862de0bde72ac82ebd164
