### ISSUE TITLE
Unable to add/remove "server backup limit" after server has been created. 

### ISSUE THREAD

**Issue by purejosh** [Jexactyl/Jexactyl#340]
### Current Behavior

If you create a server with 0 backups, and buy more backup credits, you cannot increase the backup limit on your existing server. Error message:
`You cannot add this resource because an administrator has set a maximum limit.`

If you create a server with 4 backups, and try to remove backup limits, you cannot. Again, same error: 
`You cannot add this resource because an administrator has set a maximum limit.`

### Expected Behavior

Backup limits (and probably other allocation limits) should be able to be modified after server creation. 

### Steps to Reproduce

Explained above. 

### Panel Version

3.7.3

### Wings Version

1.11.8

### Games and/or Eggs Affected

n/a

### Docker Image

n/a

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Closing for v4
