### ISSUE TITLE
First account setup using oauth with Discord doesn't give user a password

### ISSUE THREAD

**Issue by purejosh** [Jexactyl/Jexactyl#341]
### Current Behavior

So, I set up discord oauth and used a test account, which I started with discord oauth. This means I've never given it a password. Now after I'm logged in with my test account, I'm unable to do anything without setting up a password, which I can't do because I've never actually set up one.

Is this an oversight? Or did I miss something?

Obviously I can go to password reset and get a new one, but what's the point of allowing discord oauth to create a new account, but not assign the customer a password? Again, unless I missed something.

### Expected Behavior

When creating an account, it should assign a temp password, or at least have you enter a password after it creates the account. 

Another solution would be to prevent new accounts from being created using oauth, but rather allow oauth through discord to allow sign ins but not account creations. 

### Steps to Reproduce

Using a discord account who's email is not a user already, use oauth and create a new account. 
Observe that no actions can be performed until a password reset is done. 

### Panel Version

3.7.3

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Yes, this is a large oversight with this system. The original intention was to use the SMTP server to send emails containing the password, but that didn't get implemented.

**Comment by camwhi-te** [comment]
Closing for v4
