### ISSUE TITLE
/api/application/user/#/resources: Call to a member function respond() on array

### ISSUE THREAD

**Issue by fourteentrees** [Jexactyl/Jexactyl#342]
### Current Behavior

This route responds with a 500 Internal Server Error.

When enabling debug, the error goes as follows:

> Call to a member function respond() on array
Exception
Error
in [/var/www/jexactyl/app/Http/Controllers/Api/Application/Users/UserResourcesController.php ](https://dl-preview-container.pstmn.io/iframe-viewer-container/v1)(line 47)
    public function view(GetUsersRequest $request, User $user): array    {        return $this->fractal->item($user)            ->transformWith($this->getTransformer(UserResourcesTransformer::class))            ->toArray()            ->respond(201);    }    /**     * Update an existing user on the system and return the response. Returns the     * updated user model response on success. Supports handling of token revocation

### Expected Behavior

Jexactyl should return the user's resources.

### Steps to Reproduce

- Create an Application API Key
- GET /api/application/user/#/resources, substituting # with a valid user ID

### Panel Version

3.7.3

### Wings Version

1.11.8

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Closing for v4

**Comment by lotus64yt** [comment]
Why this error happend ? it is possible to manually fix it ?
