### ISSUE TITLE
Discord Oauth, Usernames must start and end with an alphanumeric character

### ISSUE THREAD

**Issue by dxomg** [Jexactyl/Jexactyl#343]
### Current Behavior

So currently when a user registers using the Oauth, it takes the existing discord username as the username for the panel, but the issue is that discord allows starting and ending with non alphanumeric characters which conflict with the existing configuration of jexactyl/pterodactyl, because if a user for example is the following "`_MyLovelyUser_`" When registering it will just simply show a blank page and without registering any error on the logs.

### Expected Behavior

The expected behaviour should be that it either changes the username to remove the starting or ending non alphanumeric numbers or either just accept it

### Steps to Reproduce

This is very simple, you need a discord username starting or ending or both on non-alphanumeric, as said before, you can take the example of this username "`_MyLovelyUser_`"

after that you just simply enable Discord Oauth and try registering with the afore mentioned discord account, it will show a white screen with no errors in it, as well as no logs mentioning the issue

### Panel Version

3.7.3

### Wings Version

1.11.11

### Games and/or Eggs Affected

Does not apply

### Docker Image

Does not apply

### Error Logs

```bash
https://bin.ptdl.co/zjekw/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by dxomg** [comment]
#106  Related
#336  Related
#89    Related

**Comment by camwhi-te** [comment]
I'll merge this PR as a quick fix as I do not plan on making any major changes to v3.x as the new version (`everest` branch) will replace this.
