### ISSUE TITLE
Add filters on API Application /servers endpoint

### ISSUE THREAD

**Issue by JarsScript** [Jexactyl/Jexactyl#347]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

It would be great if places like application/servers?filter[] added more arguments like "**user**" (ptero id) , "**node**", "**status**" and etc

Also, The possibility that in Create Server from api application, be able to create server with **renewal** and **renewable** option

**Comment by camwhi-te** [comment]
This is sorted in v4
