### ISSUE TITLE
Support for multiple alerts

### ISSUE THREAD

**Issue by kokofixcomputers** [Jexactyl/Jexactyl#355]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Add support for multiple notifications/alerts

<img width="1438" alt="Screenshot 2024-10-14 at 3 43 12 PM" src="https://github.com/user-attachments/assets/596234e9-d051-4172-96fb-37da8263114e">

I will try to implement this myself. But it doesn't look very easy, plus I'm new to typescript and php

**Comment by camwhi-te** [comment]
I see what you're saying, but this would require the alerts system to be entirely re-written and it seems like that system could become cluttered very quickly.
