### ISSUE TITLE
Earn Credits page shows currency as $ while it should be the custom set one (JCR)

### ISSUE THREAD

**Issue by RebornTrack970** [Jexactyl/Jexactyl#36]
### Current Behavior

![image](https://user-images.githubusercontent.com/62565267/177574164-b9a3857e-9cd6-489c-9b9a-0e9ba6c20678.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/62565267/177574703-b88cdef0-feae-4125-aaa0-45990ed5689d.png)

### Steps to Reproduce

*

### Panel Version

1.4.0

### Wings Version

1.4.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by RebornTrack970** [comment]
Also, it seems changing the coin name in the settings doesnt change it.

**Comment by OlekAleksander** [comment]
Also coin names dont apply at the resources purchase page
