### ISSUE TITLE
The background color in the theme is not working

### ISSUE THREAD

**Issue by Mantouisyummy** [Jexactyl/Jexactyl#360]
### Current Behavior

When adjust the background color, the preview is not adjusted.

![image](https://github.com/user-attachments/assets/404da564-7f13-426d-9365-aac0cce1ed91)

### Expected Behavior

When adjusting the background color, the preview should be adjusted as well.

### Steps to Reproduce

1. Go to Admin Page
2. Click on the Theme option and adjust the background color

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
This is known and honestly this won't be fixed because of the way the background color is handled via the Panel. See `wrapper.blade.php` for the fact that the background color is set there, which can't be dynamically updated like the React UI. This may be fixed in time
