### ISSUE TITLE
Authentication module has not been added normally

### ISSUE THREAD

**Issue by Mantouisyummy** [Jexactyl/Jexactyl#361]
### Current Behavior

When I click on any module and press “Add to Panel”, nothing happens.

### Expected Behavior

When you click “Add to Panel”, the added module should appear.

### Steps to Reproduce

1. Go to Admin Page
2. Go to the Auth page
3. Click “Add Module”, then find any module and click “Add to Panel”.

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
@Mantouisyummy I'm not able to replicate this. Can anyone else please confirm?

**Comment by Mantouisyummy** [comment]
Here's a video of the procedure I recorded at the time:
https://github.com/user-attachments/assets/90194052-ded6-495b-84e7-200ac0171607
