### ISSUE TITLE
Error “Author field is required” when creating Nest

### ISSUE THREAD

**Issue by Mantouisyummy** [Jexactyl/Jexactyl#362]
### Current Behavior

After clicking “New Nest” and filling in the name and description and clicking the “Create Nest” button, the error “The author field is required” appears.

This is Error:
![image](https://github.com/user-attachments/assets/47d1fa58-eb94-47ee-864a-4f7dc0edfdaa)

### Expected Behavior

After clicking “Create Nest”, Nest should be created correctly.

### Steps to Reproduce

1. Go to Admin Page
2. Go to Nests Page
3. Click New Nest Button
4. Click Create Nest Button

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in commit https://github.com/Jexactyl/Jexactyl/commit/8efb461cc6da3d41ba1bc69fb49c6e05fda0c746
