### ISSUE TITLE
The “Ticket System” and “Jexactyl AI” enable buttons don't work

### ISSUE THREAD

**Issue by Mantouisyummy** [Jexactyl/Jexactyl#363]
### Current Behavior

As the title, clicking the enable button does nothing

I'm not sure if it's because the feature isn't ready yet or something else, so I've decided that I'm going to submit this issue.

### Expected Behavior

Clicking the enable button should take to the corresponding page

### Steps to Reproduce

1. Go to Admin Page
2. Go to AI & Ticket page
3. Click Enable Button

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Unable to replicate but will continue investigating

**Comment by Mantouisyummy** [comment]
@camwhit-e 

Here's a video of the procedure I recorded at the time:
https://github.com/user-attachments/assets/c4fb2021-a50d-4382-8a12-59420004d90a
