### ISSUE TITLE
When server error occurs, clicking “Ask AI” Button will load indefinitely.

### ISSUE THREAD

**Issue by Mantouisyummy** [Jexactyl/Jexactyl#364]
### Current Behavior

When a server error occurs and the “Ask AI” button appears, clicking it will keep loading indefinitely.
and the browser console will show the following error:

![image](https://github.com/user-attachments/assets/d5e227ed-0a66-4fb5-a876-d0bb743cf349)

### Expected Behavior

After clicking “Ask AI”, the AI will generate a response to this error.

### Steps to Reproduce

1. Go to Server Page
2. Click Ask AI Button

### Panel Version

v4.0.0-beta1

### Wings Version

1.11.13

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
@Mantouisyummy A Laravel log would be very useful here:

`tail -n 1000 /var/www/jexactyl/storage/logs/laravel-$(date +%F).log | grep "\[$(date +%Y)"`

**Comment by Mantouisyummy** [comment]
This is an error log:
[2024-12-24 09:05:01] production.ERROR: The Jexactyl AI module is not enabled. {"userId":10,"exception":"[object] (Exception(code: 0): The Jexactyl AI module is not enabled. at /var/www/jexactyl-everest/app/Http/Controllers/Api/Client/Servers/AIController.php:28)

I already pressed “Enable Jexactyl AI” button.

But I think it has something to do with #363
