### ISSUE TITLE
No logout button on everest

### ISSUE THREAD

**Issue by GamingBaeren** [Jexactyl/Jexactyl#368]
### Current Behavior

No logout button 

### Expected Behavior

A logout button 

### Steps to Reproduce

Not a logout button 

### Panel Version

4.0.0beta2

### Wings Version

1.11.11

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in latest commit
