### ISSUE TITLE
Admin Panel - Server Allocations

### ISSUE THREAD

**Issue by TheGamer3514** [Jexactyl/Jexactyl#370]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

![image](https://github.com/user-attachments/assets/7c574d7c-666c-4715-809c-9b879150be2f)
Would be nice  if instead it says to start searching / lists them without a search like jexactyl v3 does. Right now it could be a bit confusing and give the idea to the admin that no allocations are left, even when there are

**Comment by TheGamer3514** [comment]
Put as feature request as it isn't really a bug

**Comment by camwhi-te** [comment]
This has been changed for the next beta release, users can now input a range of allocations to create.
