### ISSUE TITLE
Ticket Limit 

### ISSUE THREAD

**Issue by TheGamer3514** [Jexactyl/Jexactyl#371]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

There is seemingly no limit on how many tickets one user can open. It would be nice if panel admins were able to set a limit, to prevent spam (v4)

### Additional context to this request.

This was a thing in v3, but either I failed to find the setting or it does not exist

**Comment by camwhi-te** [comment]
This feature does actually exist, it just hasn't been implemented in the UI. Will add.

**Comment by camwhi-te** [comment]
Resolved in  https://github.com/Jexactyl/Jexactyl/commit/dca625301e478a00775294c01302f7fc8f466ab1
