### ISSUE TITLE
Ability To cancel setup - Admin

### ISSUE THREAD

**Issue by TheGamer3514** [Jexactyl/Jexactyl#374]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

On admin pages such as billing, there is no option to cancel things like "Configure Stripe API" and setting api keys. It would if there was a cancel button, instead of what you currently have to do of input something random, then disable or go off the page via url.
![image](https://github.com/user-attachments/assets/921992dd-8341-49a6-ab0a-6265cc321a1e)

**Comment by camwhi-te** [comment]
Resolved in https://github.com/Jexactyl/Jexactyl/commit/5f0a965239a603423aa078637445e25b447d9360
