### ISSUE TITLE
Cannot change ram using the resources tab in user settings

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#4]
### Current Behavior

If you want to set the ram of an user, it doesnt save - other options work.

### Expected Behavior

For it to save

### Steps to Reproduce

Go to admin panel > users > select an user > resources > ram

### Panel Version

3.0.1

### Wings Version

1.6.2

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Fixed in 40867f753ceba0ae5dbcd997893ca7f2cf0d0467
