### ISSUE TITLE
Admin Logs

### ISSUE THREAD

**Issue by PenguCCN** [Jexactyl/Jexactyl#41]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Show a log in admin area of certain actions done by users with admin permissions. 

(Deleting servers, Creating servers, changing account owners, creating users, ect)

### Describe the solution you'd like.

Just a little page in the admin area similar to how frontend shows login logs or file logs for servers

**Comment by Karbon1** [comment]
yes please add it

**Comment by ParallaxOnline** [comment]
+1 to this, Maybe add the ability for the events to be sent to a discord/slack webhook as well.

**Comment by FungY911** [comment]
+1

**Comment by ItzExotical** [comment]
+1 Would be amazing to ensure that the staff members are not abusing.

**Comment by camwhi-te** [comment]
Alternatively, people could just trust their admins
Moving this to low priority due to size of work

**Comment by ParallaxOnline** [comment]
There is trust, But logging is standard practice and shouldn't be seen as low priority.

**Comment by philip44373** [comment]
+1 this would be really good I don't see why its low priority.

**Comment by camwhi-te** [comment]
This feature is coming to v4, closing
