### ISSUE TITLE
Git version control tab

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#43]
### Is there an existing feature request for this?

- [x] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

A tab wich allows to commit/pull changes from a public/private repo.

### Describe the solution you'd like.

A tab in the server page navigation with a list of recent commits

**Comment by camwhi-te** [comment]
With eggs, you can create variables which allow you to pull from a private or public Git repo. Reference the Discord.JS egg in [this repo](https://github.com/parkervcp/eggs) as an example.
