### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by r-kjha** [Jexactyl/Jexactyl#45]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please document the API endpoints of Jexactyl.

### Describe the solution you'd like.

You can leave the pterodactyl part and only do the one's that are specific for pterodactyl. People can use the pterodactyl api docs for the rest.

**Comment by camwhi-te** [comment]
This will be worked on at `jexactyl/api-docs`
