### ISSUE TITLE
Plugin manager doesn't work

### ISSUE THREAD

**Issue by r-kjha** [Jexactyl/Jexactyl#50]
### Current Behavior

1. The link to the plugins on the spigot website does not open in the new tab.
2.  nothing happens after clicking okay on plugin install confirmation.
![image](https://user-images.githubusercontent.com/87710356/179003601-18587642-8f5b-49ad-88ce-b0f6199041bb.png)
3. If the plugin is not found, it shows this error. A more user-friendly message would be better for 404 plugins not found.
![image](https://user-images.githubusercontent.com/87710356/179003790-4ac56e0d-f904-4d9a-9710-d05454a660e3.png)

### Expected Behavior

Described above.

### Steps to Reproduce

The default behavior for all panels running the latest version.

### Panel Version

3.2.2

### Wings Version

1.6.4

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
I will need more information to work with than 'it doesn't work'. Please post error logs via this command:
`tail -n 100 /var/www/jexactyl/storage/logs/laravel-$(date +%F).log | nc bin.ptdl.co 99`

**Comment by ghost** [comment]
1st is fixed.
2nd fix is on way after u post logs
3rd in the next update maybe.

**Comment by OlekAleksander** [comment]
Its seems to be an issue with your panel as on my friends host it works

**Comment by camwhi-te** [comment]
Unable to reproduce issue
