### ISSUE TITLE
Cannot install another plugin with same query without refreshing

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#57]
### Current Behavior

Can't install the plugin if we didn't change our search query.

### Expected Behavior

Can install plugins with the same search query.

### Steps to Reproduce

1: Goto plugin installer.
2: Search anything for example ``meow``.
3: Install any plugin from that search query and you will see that it is now installed.
4: Now install another plugin without refreshing the page you will notice it is not installing.

### Panel Version

Lasted

### Wings Version

Lasted

### Error Logs

```bash
No errors since idk
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
I'll need error logs in order to work with this.

**Comment by ghost** [comment]
There are no error logs.

**Comment by camwhi-te** [comment]
Unable to investigate this further without any information
