### ISSUE TITLE
Broken Egg

### ISSUE THREAD

**Issue by Alanilily** [Jexactyl/Jexactyl#66]
### Current Behavior

If you go from minecrafts category to gta for example the first egg will be broken until u switch back to itwhat basically happens is that it creates a bungeecord or paper server instead of the five egg or any other egg

### Expected Behavior

I think this is pretty clear u expect it to work like normal when u switch to a new category u don't have to switch to another egg then back to use the egg u wanna use without problems

### Steps to Reproduce

u go to create a server enter in your specs etc. then go to server nest go from Minecraft to any other category the first egg that pops up when u switch will be temp broken until u choose another egg then go back to it

### Panel Version

3.2.3

### Wings Version

1.6.4

### Games and/or Eggs Affected

All

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by cmrxnn** [comment]
This issue has already been fixed and will be released soon.
