### ISSUE TITLE
Add PLN

### ISSUE THREAD

**Issue by MrKubuS** [Jexactyl/Jexactyl#67]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Please add PLN (Polish zloty)

### Describe the solution you'd like.

Please add PLN (Polish zloty)

**Comment by OlekAleksander** [comment]
Modify panels files.

**Comment by camwhi-te** [comment]
Adding documentation on implementing support for additional currencies soon. It's a modification that only requires 1-2 lines to be made, so it's not something that needs to be embedded directly into this Panel.
