### ISSUE TITLE
Console Enabled During Install / Transfer

### ISSUE THREAD

**Issue by PenguCCN** [Jexactyl/Jexactyl#68]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Since Console no longer shows up during server install and transfer, me and my clients no longer have the ability to see the progress made. So, for example, if I'm moving a client to a new location, I no longer have the ability to see how much is done so I can give an estimated time

### Describe the solution you'd like.

Bring back console showing up during these processes

**Comment by babyharpsea** [comment]
It would be great, not sure why it got removed, or just make it only visible to admins like it was

**Comment by camwhi-te** [comment]
It got removed due to the way the popout console system is designed. I'll try and find a way around it.

**Comment by babyharpsea** [comment]
Is it possible to view the console by adding /console at the end of the URL then?

**Comment by camwhi-te** [comment]
Yeah - I'll just handle it differently. Current implementation isn't very effective.

**Comment by babyharpsea** [comment]
Tried adding /console to the end of the URL when transferring. Didn't work. Still getting the transferring screen.

**Comment by philip44373** [comment]
+1

**Comment by Ashu11-A** [comment]
I make Eggs from time to time, and seeing the Console during startup is very important +1

**Comment by camwhi-te** [comment]
Fixed for next release
