### ISSUE TITLE
Resource transferral

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#69]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In this feature, users can be able to gift resources to another user.

### Describe the solution you'd like.

Make something like input username and resources things on the resources tab.

### Additional context to this request.

Null

**Comment by TheFallenSpirit** [comment]
Sounds like a good idea.

**Comment by camwhi-te** [comment]
Not going to be implementing this, just doesn't seem necessary and opens up more room for attack vectors. Sorry.
