### ISSUE TITLE
Changing coins name (JCR = to something else)

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#7]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In the admin dashboard there should be an option to change the store currency (coins name)

### Describe the solution you'd like.

Create an way to change the coins name in admin dashboard - without modifying files

### Additional context to this request.

![image](https://user-images.githubusercontent.com/66617078/174434556-9b32494d-7934-4d61-9975-e4dde88d2f3e.png)

**Comment by camwhi-te** [comment]
Resolved in f57183bc87b797750418ec78e4dea0d0f8f8be5f
