### ISSUE TITLE
The minimum for renewing a server is 1

### ISSUE THREAD

**Issue by Anttonw** [Jexactyl/Jexactyl#77]
### Current Behavior

It is not possible to set a value of 0 to renew a server.

### Expected Behavior

That there was an option to renew the servers for free.

### Steps to Reproduce

-

### Panel Version

3.3

### Wings Version

1.7

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by Antoniovbn000** [comment]
it would be nice if jex make this possible
