### ISSUE TITLE
PaymentWall Gateway

### ISSUE THREAD

**Issue by Paquito86** [Jexactyl/Jexactyl#79]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

PaymentWall is an excellent solution in order to accept payments worldwide adding it to Jexactyl would be a great addition.

### Describe the solution you'd like.

I would like to see it implemented with the other gateways, so customers can choose.

### Additional context to this request.

We have a big market in South America and the best way for them to pay is using the PaymentWall gateway. I would really like to get PaymentWall as an option.

**Comment by camwhi-te** [comment]
PaymentWall's API library for PHP has not been updated in over 3 years, and is unlikely to see future updates. As a result of this, I'm not going to implement this gateway - sorry for the inconvenience.

**Comment by Paquito86** [comment]
Reasonable. They should keep the library updated. Thank you for the quick response!
