### ISSUE TITLE
Show active page on sidebar

### ISSUE THREAD

**Issue by OlekAleksander** [Jexactyl/Jexactyl#8]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Show what page the user is on

### Describe the solution you'd like.

![image](https://user-images.githubusercontent.com/66617078/174434847-b1ccfec8-4617-416d-b317-d8b32240fac1.png)
or something like that
![image](https://user-images.githubusercontent.com/66617078/174434874-323e7838-db61-42c9-9397-069cf3d1a0b9.png)

**Comment by camwhi-te** [comment]
Closed in 3f38d8da05648e66f0f545ab25ee7dfbe54cd289
