### ISSUE TITLE
Role based access to features

### ISSUE THREAD

**Issue by lucatolton** [Jexactyl/Jexactyl#83]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

The ability to create roles for users which can be assigned and revoked on the admin panel.
With the roles, you will be able to control which features of the panel users can access, such as limiting ports or databases to premium users, and only allowing people with 2FA on to delete servers.
This could also allow for easier resource allocation, by giving let's say a premium role an extra gigabyte of resources, of which the role could be handed out by a payment system using the Jexactyl API.

### Describe the solution you'd like.

A page for admins to manage roles, assign them to users and see which roles users have.

**Comment by camwhi-te** [comment]
As discussed this'll be marked as unlikely due to the complexity.

**Comment by camwhi-te** [comment]
Closing - may be opened in future
