### ISSUE TITLE
User Approvals

### ISSUE THREAD

**Issue by ColdDev** [Jexactyl/Jexactyl#84]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Similar to GitLab self-hosted instances, I think it would be cool for Jexactyl to add the ability to approve users when they register. This would allow for servers to have a registration page for any admins that may require console access, with minimal interference from the owner/admin of the panel.

### Describe the solution you'd like.

The solution would be implemented via a section in the admin page (possibly in User Registration) where there would be a list of users that are waiting to be approved, and then once they're approved they can use the panel as normal.

### Additional context to this request.

See [here](https://docs.gitlab.com/ee/user/admin_area/moderate_users.html) to look at how GitLab implements this functionality.

**Comment by camwhi-te** [comment]
This would likely slow down the process of users being able to join, and take more time for administrators to approve users. Therefore this is relatively unlikely to be implemented.

**Comment by ColdDev** [comment]
> This would likely slow down the process of users being able to join, and take more time for administrators to approve users. Therefore this is relatively unlikely to be implemented.

Well, I don't see how it would slow down the ability for users to sign up to a panel if it's turned off by default. Perhaps I didn't make it clear in my original description however I meant it in a way where it would be a toggleable thing, probably off by default, and not forced.

**Comment by camwhi-te** [comment]
![image](https://user-images.githubusercontent.com/72230943/184028529-1e5a0325-2d87-4789-b6d7-868ae67b8a5d.png)

**Comment by camwhi-te** [comment]
Will ensure this is customizable and turned **off** by default.

**Comment by ColdDev** [comment]
> ![image](https://user-images.githubusercontent.com/72230943/184028529-1e5a0325-2d87-4789-b6d7-868ae67b8a5d.png)

This looks awesome! Thanks for implementing this so fast :)
