### ISSUE TITLE
Admin pages takes way too long to load

### ISSUE THREAD

**Issue by Alanilily** [Jexactyl/Jexactyl#86]
### Current Behavior

If more than 20 or 100 servers are on the panel the /admin might take 6 secs to over 20 secs long to load which is insane!

### Expected Behavior

I think its pretty obvious here that it should take under 1 sec to load

### Steps to Reproduce

Get 20 or over 100 servers to run on it and most of them should be online

### Panel Version

3.3.1

### Wings Version

1.7.0

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by TheFallenSpirit** [comment]
What are the specs of your web server?

**Comment by Alanilily** [comment]
It is 16 Cores 32GB Ram 320GB Disk

**Comment by cmrxnn** [comment]
Does restarting PHP's webserver help?
`systemctl restart --now php8.0-fpm` (replace 8.0 with your PHP version `php -v`)

**Comment by cmrxnn** [comment]
@Alanilily This issue may be closed if a relevant reply is not given, just to let you know.

**Comment by Alanilily** [comment]
Yes sorry for the no replies but im waiting to encounter it again so i can try it and see if it fixes it.

**Comment by r-kjha** [comment]
I recently updated my panel and now I am unable to access the admin area. It just keeps loading forever. The rest of the other pages work fine.

**Comment by r-kjha** [comment]
I just realized that only `https://domain.com/admin` is unaccessible and keeps loading forever. I can access other admin pages like `https://domain.com/admin/databases`, `https://domain.com/admin/api` ,etc fine.

**Comment by Alanilily** [comment]
> I just realized that only `https://domain.com/admin` is unaccessible and keeps loading forever. I can access other admin pages like `https://domain.com/admin/databases`, `https://domain.com/admin/api` ,etc fine.

Yes that is what i meant

**Comment by Alanilily** [comment]
> Does restarting PHP's webserver help? `systemctl restart --now php8.0-fpm` (replace 8.0 with your PHP version `php -v`)

So the admin page starts taking very long to load until it finally gives a server error 500 which i just got and restarting php doesnt work
