### ISSUE TITLE
Blank White Page on Discord Login after Update

### ISSUE THREAD

**Issue by r-kjha** [Jexactyl/Jexactyl#89]
### Current Behavior

It shows a blank, white page when we try to log in with discord. Email signup and login works fine.  This occurred after updating to the latest version.

https://domain.com/auth/discord/callback?code=bigrandomcode
![image](https://user-images.githubusercontent.com/87710356/184476851-82bf1f50-3282-424d-843c-51e489a5c59a.png)
 

### Expected Behavior

Login without the white blank page without any issue

### Steps to Reproduce

Should be default to all panels running latest version

### Panel Version

3.4.1

### Wings Version

1.7.0

### Error Logs

```bash
https://bin.ptdl.co/elqsl/
```

### Is there an existing issue for this?

- [X] I have searched the existing issues before opening this issue.
- [X] I have provided all relevant details, including the specific game and Docker images I am using if this issue is related to running a server.
- [X] I have checked in the Discord server and believe this is a bug with the software, and not a configuration issue with my specific system.

**Comment by camwhi-te** [comment]
Unable to reproduce.
