### ISSUE TITLE
Pull users into discord server(s)

### ISSUE THREAD

**Issue by Alanilily** [Jexactyl/Jexactyl#90]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Basically you can add in a guild id where if a person authenticates they will be pulled into that server if the auth bot is in that server

### Describe the solution you'd like.

Add a new category like auto joins or smth where u can enable it and add the guild id u want ppl to be pulled into upon authenticating with discord

**Comment by cmrxnn** [comment]
Not implementing this, may make an addon in the future to do this.
