### ISSUE TITLE
Ability to add your own products

### ISSUE THREAD

**Issue by bbig2748** [Jexactyl/Jexactyl#95]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Hello.

I have a propose to add to Jexactyl the ability to add your own products (servers) as it is done via the "Billing Addon" to a normal Pterodactyl.

### Describe the solution you'd like.

add own products do "shop"

**Comment by camwhi-te** [comment]
Jexactyl is designed to be pay-as-you-go, not pro-rata billing. Not implementing this.
