### ISSUE TITLE
Add custom amount of resources

### ISSUE THREAD

**Issue by kry008** [Jexactyl/Jexactyl#96]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

In admin panel you can adjust what amount of resources will be given with credits. Because it is only 1GB RAM addon, and it will be nice if in admin panel i will able to change it.

### Describe the solution you'd like.

In admin panel you can adjust what amount of resources will be given with credits. Because it is only 1GB RAM addon, and it will be nice if in admin panel i will able to change it.

**Comment by camwhi-te** [comment]
This is configurable.
