### ISSUE TITLE
Add fees for setting servers for different eggs

### ISSUE THREAD

**Issue by kry008** [Jexactyl/Jexactyl#97]
### Is there an existing feature request for this?

- [X] I have searched the existing issues before opening this feature request.

### Describe the feature you would like to see.

Option in egg/panel for setting new server with fee. 

### Describe the solution you'd like.

When setting/buying, new server account will be charged with given amount of credits

**Comment by OlekAleksander** [comment]
Server slot is like a fee for creation

**Comment by camwhi-te** [comment]
Refer to above comment

**Comment by kry008** [comment]
But for example I have Minecraft server and I want to set up fee set at 50 points and for example terraria where I want only 10
