### ISSUE TITLE
Coupon system

### ISSUE THREAD

**Issue by ghost** [Jexactyl/Jexactyl#98]
### Is there an existing feature request for this?

- [X] #104

### Describe the feature you would like to see.

I could like to have a coupon system so we(admins) can create coupon codes having some amount of resources. And it should have a time limit so it cant be only for one-time use. And we can set a time limit and update if it is a one-time code or not.

### Describe the solution you'd like.

A separate page with that system both in admin and client, and also a button to revoke coupons and check the box if that is for one-time use or not.

### Additional context to this request.

Meow

**Comment by camwhi-te** [comment]
Too similar to referral system, closing

**Comment by ghost** [comment]
Nah it is not.

**Comment by OlekAleksander** [comment]
No its not.

**Comment by ghost** [comment]
+1

**Comment by AndyIsHereBoi** [comment]
I would also like this. I do not see how this is similar to the referral system at all.

**Comment by lavabyte** [comment]
How to remove the coupon?
